changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Security
      labels:
        - security
    - title: Performance
      labels:
        - performance
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
        - compatibility
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Internal
      labels:
        - internal
    - title: Other changes
      labels:
        - "*"
