#!/bin/bash
# Run every audit fixture and emit a consolidated summary.
# Iteration order is stable so re-runs produce comparable output.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"

IS_WINDOWS=0
case "${OSTYPE:-}" in
    msys*|cygwin*|win32*) IS_WINDOWS=1 ;;
esac
case "${OS:-}" in
    Windows_NT) IS_WINDOWS=1 ;;
esac

python_path() {
    if [[ $IS_WINDOWS -eq 1 ]] && command -v cygpath &>/dev/null; then
        cygpath -w "$1"
    else
        printf '%s\n' "$1"
    fi
}

json_field_or_default() {
    local path="$1"
    local field="$2"
    local default="$3"
    if [[ ! -f "$path" ]]; then
        printf '%s\n' "$default"
        return
    fi
    PY_JSON_FILE="$(python_path "$path")" PY_JSON_FIELD="$field" PY_JSON_DEFAULT="$default" python3 - <<'PY'
import json
import os

with open(os.environ["PY_JSON_FILE"]) as handle:
    data = json.load(handle)
print(data.get(os.environ["PY_JSON_FIELD"], os.environ["PY_JSON_DEFAULT"]))
PY
}

# Wipe the work-dir parent ONCE at suite start. `run-audit.sh` already
# wipes `/tmp/lpm-audit-work/<fixture>-<mode>/` per fixture, but it
# does not clean the parent — so a previous suite run that ever
# populated `/tmp/lpm-audit-work/.lpm/wrappers/` (e.g., a fixture's
# `lpm install` cwd-relative behavior, or a manual debug session)
# leaves leftover wrappers that Node's symlink walk-up resolves
# through. That produced false-positive PASSes for fixtures missing
# real peer deps in their package.json — see 4b's
# `peer-heavy/apollo-graphql`, `tooling/eslint-flat-config`, and
# `workspace/monorepo-basic` archaeology. Wiping the parent makes
# every suite run fixture-isolated and the baseline trustworthy.
# — same fallback chain as run-audit.sh (RUNNER_TEMP for
# windows-latest CI, /tmp on Linux/macOS).
WORK_PARENT="${LPM_AUDIT_WORK_BASE:-${RUNNER_TEMP:-/tmp}/lpm-audit-work}"
rm -rf "$WORK_PARENT"

# All fixtures, deterministically ordered.
# `top-npm/*` is intentionally omitted here — those fixtures are
# auto-generated by bench/top-npm-audit/generate.sh and run via
# bench/top-npm-audit/run-all.sh on workflow_dispatch only. Including
# them in this curated suite would inflate every-PR CI time by ~10x.
FIXTURES=(
    "peer-heavy/react-ssr"
    "peer-heavy/vite-react"
    "peer-heavy/nextjs-minimal"
    "peer-heavy/vue-3-ecosystem"
    "peer-heavy/apollo-graphql"
    "peer-heavy/nestjs-deep"
    "peer-heavy/optional-peers"
    "peer-heavy/auto-install-peer"
    "tooling/eslint-flat-config"
    "tooling/babel-presets"
    "tooling/rollup-plugins"
    "native/sharp-image"
    "native/esbuild-prebuilt"
    "native/better-sqlite3"
    "native/prisma-codegen"
    "workspace/monorepo-basic"
    "workspace/cyclic-deps"
    "workspace/large-monorepo"
    "dogfood/realworld-app"
    "source-kind/file-protocol"
    "source-kind/link-protocol"
    "source-kind/postinstall-sibling-husky"
    "source-kind/bundle-deps"
    "source-kind/npm-aliases"
    "source-kind/overrides"
    "source-kind/patches"
    "source-kind/postinstall-introspects-layout"
    "source-kind/self-referential"
)

declare -a RESULTS=()
declare -a FIXTURE_NAMES=()

date
echo "[audit] running all ${#FIXTURES[@]} fixtures"
echo

for fixture in "${FIXTURES[@]}"; do
    echo
    echo "=========================================="
    echo "  $fixture"
    echo "=========================================="
    set +e
    output=$("$HERE/run-audit.sh" "$fixture" 2>&1)
    exit_code=$?
    set -e
    echo "$output"

    fixture_name="$(echo "$fixture" | tr '/' '-')"
    iso=$(ls -t "$HERE/results/$fixture_name-isolated-"*.json 2>/dev/null | head -1)
    hst=$(ls -t "$HERE/results/$fixture_name-hoisted-"*.json 2>/dev/null | head -1)
    iso_verdict=$(json_field_or_default "$iso" verdict "?")
    hst_verdict=$(json_field_or_default "$hst" verdict "?")
    FIXTURE_NAMES+=("$fixture")
    RESULTS+=("${iso_verdict}/${hst_verdict}")
done

# Consolidated summary
echo
echo
echo "############################################"
echo "##  CONSOLIDATED AUDIT SUMMARY"
echo "############################################"
printf "%-44s %-20s %s\n" "FIXTURE" "ISOLATED/HOISTED" "CATEGORY"
echo "------------------------------------------------------------------"
pass_count=0
skip_count=0
symmetric_non_pass=0
asymmetric_count=0
symmetric_issue_rows=()
asymmetric_rows=()
for i in "${!FIXTURE_NAMES[@]}"; do
    fixture_name="$(echo "${FIXTURE_NAMES[$i]}" | tr '/' '-')"
    iso_file=$(ls -t "$HERE/results/$fixture_name-isolated-"*.json 2>/dev/null | head -1)
    hst_file=$(ls -t "$HERE/results/$fixture_name-hoisted-"*.json 2>/dev/null | head -1)
    iso_c=$(json_field_or_default "$iso_file" classification "?")
    hst_c=$(json_field_or_default "$hst_file" classification "?")
    if [[ "$iso_c" == "$hst_c" ]]; then
        category_summary="$iso_c"
    else
        category_summary="$iso_c/$hst_c"
    fi
    printf "%-44s %-20s %s\n" "${FIXTURE_NAMES[$i]}" "${RESULTS[$i]}" "$category_summary"
    case "${RESULTS[$i]}" in
        "PASS/PASS") pass_count=$((pass_count+1)) ;;
        "SKIP/SKIP") skip_count=$((skip_count+1)) ;;
        PASS/FAIL|FAIL/PASS|PASS/SKIP|SKIP/PASS|FAIL/SKIP|SKIP/FAIL)
            asymmetric_count=$((asymmetric_count+1))
            asymmetric_rows+=("${FIXTURE_NAMES[$i]}|${RESULTS[$i]}")
            ;;
        *)
            symmetric_non_pass=$((symmetric_non_pass+1))
            symmetric_issue_rows+=("${FIXTURE_NAMES[$i]}|$category_summary|${RESULTS[$i]}")
            ;;
    esac
done
echo "------------------------------------------------------------------"
printf "PASS both: %d   SKIP: %d   ASYMMETRIC: %d   SYMMETRIC NON-PASS: %d   total: %d\n" \
    "$pass_count" "$skip_count" "$asymmetric_count" "$symmetric_non_pass" "${#FIXTURE_NAMES[@]}"
echo

if [[ ${#symmetric_issue_rows[@]} -gt 0 ]]; then
    echo "Symmetric non-pass buckets:"
    python3 -c '
import collections
import sys

rows = [row.split("|", 2) for row in sys.argv[1:] if row]
by_category = collections.defaultdict(list)
for fixture, category, verdicts in rows:
    by_category[category].append((fixture, verdicts))

for category in sorted(by_category):
    entries = sorted(by_category[category])
    print(f"  {category}: {len(entries)}")
    for fixture, verdicts in entries:
        print(f"    {fixture} ({verdicts})")
' "${symmetric_issue_rows[@]}"
    echo
fi

if [[ ${#asymmetric_rows[@]} -gt 0 ]]; then
    echo "Asymmetric outcomes (mode regressions):"
    for row in "${asymmetric_rows[@]}"; do
        fixture="${row%%|*}"
        verdicts="${row#*|}"
        echo "  $fixture ($verdicts)"
    done
    echo
fi

# CI exit semantics: asymmetric outcomes (PASS/FAIL or FAIL/PASS) ARE
# regressions and exit non-zero. Symmetric outcomes (both PASS or both
# FAIL or both SKIP) are not — the audit's question is "does hoisted
# regress vs isolated," and equal-outcome failures across modes are
# adjacent bugs, not hoisting regressions.
asymmetric=0
for v in "${RESULTS[@]}"; do
    case "$v" in
        PASS/FAIL|FAIL/PASS|PASS/SKIP|SKIP/PASS|FAIL/SKIP|SKIP/FAIL)
            asymmetric=$((asymmetric+1))
            ;;
    esac
done

date

if [[ $asymmetric -gt 0 ]]; then
    echo
    echo "FAIL: $asymmetric fixture(s) had asymmetric outcomes (mode regressions)"
    exit 1
fi
exit 0
