use clap::{Args, Parser, Subcommand};
use lpm_common::LpmError;

#[derive(Args)]
pub(super) struct Environment {
    #[arg(long, value_parser = clap::builder::NonEmptyStringValueParser::new())]
    pub env: Option<String>,
}

#[derive(Args)]
pub(super) struct Scope {
    /// Validate the selected command stage.
    #[arg(long, value_parser = stage_name)]
    pub stage: Option<lpm_env::EnvStage>,
    /// Validate a named service within the selected environment and stage.
    #[arg(long, value_parser = service_name)]
    pub service: Option<String>,
}

fn stage_name(value: &str) -> Result<lpm_env::EnvStage, String> {
    lpm_env::EnvStage::parse(value)
        .ok_or_else(|| "stage must be development, build, runtime, ci, or test".into())
}
fn service_name(value: &str) -> Result<String, String> {
    lpm_env::resolver::validate_env_name(value)?;
    Ok(value.into())
}

#[derive(Parser)]
#[command(name = "lpm env")]
struct LocalCommand {
    #[command(subcommand)]
    action: LocalAction,
}

#[derive(Subcommand)]
pub(super) enum LocalAction {
    Set {
        #[command(flatten)]
        environment: Environment,
        #[arg(required = true, num_args = 1.., value_name = "KEY=VALUE")]
        assignments: Vec<String>,
    },
    Get {
        #[command(flatten)]
        environment: Environment,
        key: String,
        #[arg(long)]
        reveal: bool,
    },
    List {
        #[command(flatten)]
        environment: Environment,
        #[arg(long)]
        reveal: bool,
    },
    Delete {
        #[command(flatten)]
        environment: Environment,
        #[arg(required = true, num_args = 1..)]
        keys: Vec<String>,
    },
    Import {
        #[command(flatten)]
        environment: Environment,
        file: String,
        #[arg(long)]
        overwrite: bool,
    },
    Export {
        #[command(flatten)]
        environment: Environment,
        file: String,
        #[arg(long)]
        ci: bool,
    },
    Print {
        #[command(flatten)]
        environment: Environment,
        #[command(flatten)]
        scope: Scope,
        #[arg(long, value_parser = print_format)]
        format: Option<lpm_env::PrintFormat>,
        #[arg(long)]
        schema_only: bool,
        /// Print only declared browser-visible variables.
        #[arg(long)]
        client_only: bool,
        #[arg(long, conflicts_with_all = ["format", "schema_only", "client_only", "stage", "service"])]
        ci: bool,
    },
    Example {
        #[command(flatten)]
        environment: Environment,
    },
    Check {
        #[command(flatten)]
        environment: Environment,
        #[command(flatten)]
        scope: Scope,
    },
    /// Check stored key names against .env.example.
    Validate {
        #[arg(long)]
        strict: bool,
    },
    /// Check declarations and imports without reading environment values.
    Schema,
    /// Generate separate typed server and client environment modules.
    Generate {
        #[command(flatten)]
        environment: Environment,
        #[command(flatten)]
        scope: Scope,
        #[arg(long, default_value = "env.generated")]
        out_dir: std::path::PathBuf,
        #[arg(long, default_value = "default", value_parser = adapter)]
        adapter: lpm_env_codegen::Adapter,
        /// Check every generated byte without changing files or acquiring locks.
        #[arg(long)]
        check: bool,
    },
    Init {
        #[arg(long)]
        force: bool,
    },
    Ls,
    Log,
    Unpair,
    Diff {
        #[arg(num_args = 0..=2)]
        environments: Vec<String>,
    },
    #[command(alias = "cp")]
    Copy {
        source: String,
        target: String,
        #[arg(long)]
        overwrite: bool,
    },
}

pub(super) fn parse(args: &[&str], json_output: bool) -> Result<Option<LocalAction>, LpmError> {
    if !matches!(
        args.first().copied(),
        Some(
            "set"
                | "get"
                | "list"
                | "delete"
                | "import"
                | "export"
                | "print"
                | "example"
                | "check"
                | "validate"
                | "schema"
                | "generate"
                | "init"
                | "ls"
                | "copy"
                | "cp"
                | "log"
                | "unpair"
                | "diff"
        )
    ) {
        return Ok(None);
    }
    LocalCommand::try_parse_from(std::iter::once("lpm env").chain(args.iter().copied()))
        .map(|command| Some(command.action))
        .map_err(|error| {
            let status = if error.use_stderr() { 2 } else { 0 };
            if json_output && error.use_stderr() {
                let action = if args[0] == "cp" { "copy" } else { args[0] };
                let hint = format!("Run `lpm env {action} --help` for usage.");
                crate::cli::print_json_clap_error(&error, Some(&hint));
            } else {
                let _ = error.print();
            }
            LpmError::ExitCode(status)
        })
}

fn adapter(value: &str) -> Result<lpm_env_codegen::Adapter, String> {
    lpm_env_codegen::Adapter::parse(value)
        .ok_or_else(|| "adapter must be default, node, nextjs, or vite".into())
}

fn print_format(value: &str) -> Result<lpm_env::PrintFormat, String> {
    lpm_env::PrintFormat::parse(value).ok_or_else(|| {
        format!(
            "unknown format: '{value}'. Available: {}",
            lpm_env::PrintFormat::all_names()
        )
    })
}
