[package]
name = "lpm-migrate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Lockfile and workspace migration helpers for the LPM Rust client"
license.workspace = true

[dependencies]
lpm-lockfile.workspace = true
lpm-common.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
glob = { workspace = true }
tracing = { workspace = true }
tempfile = "3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]

[lints]
workspace = true
