[package]
name = "lpm-migrate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Lockfile and workspace migration helpers for the LPM Rust client"
license.workspace = true

[dependencies]
lpm-lockfile.workspace = true
lpm-common.workspace = true
lpm-semver.workspace = true
lpm-workspace.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
serde_json_lenient = "0.2.4"
serde_yaml = "0.9"
tracing = { workspace = true }
tempfile = "3"
cap-std = "4.0.2"
cap-fs-ext.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]

[lints]
workspace = true
