[package]
name = "lpm-security"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Security auditing, provenance verification, and trust policies for LPM"

[dependencies]
lpm-common = { workspace = true }
lpm-lockfile = { workspace = true }
lpm-workspace = { path = "../lpm-workspace" }
cap-fs-ext = { workspace = true }
cap-std = "4.0.2"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
strsim = { workspace = true }
rayon = { workspace = true }
regex = "1"
ignore = { workspace = true }
bytecount = "0.6"
chrono = { workspace = true }
sha2 = { workspace = true }
shlex = { workspace = true }
time = { version = "0.3", features = ["formatting", "parsing"] }
tracing = { workspace = true }
oxc_allocator = "=0.128.0"
oxc_ast = "=0.128.0"
oxc_ast_visit = "=0.128.0"
oxc_parser = "=0.128.0"
oxc_span = "=0.128.0"

[dev-dependencies]
criterion = "0.5"
serde_json = { workspace = true }
tempfile = "3"

[[bench]]
name = "behavioral"
harness = false

[lints]
workspace = true
