#!/bin/bash
# Generate one single-dep fixture per package in top-100.txt.
# confidence-followup Each generated fixture is a
# `package.json` with a single dependency at `latest` plus a `smoke.sh`
# that delegates to the audit-fixtures-style require() check.
#
# The generated fixtures live under
# `bench/audit-fixtures/top-npm/<safe-pkg-name>/` so the existing
# `run-audit.sh` harness can drive them without modification — the
# only difference vs the curated audit-fixtures bucket is volume
# (100+ fixtures vs 28) and the workflow_dispatch-only CI gating.
#
# Output dir is gitignored. Re-running this script overwrites the
# previous generation; lockfiles in cache/store stay out of scope.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
LIST="$HERE/top-100.txt"
DEST_ROOT="$HERE/../audit-fixtures/top-npm"

if [[ ! -f "$LIST" ]]; then
    echo "ERROR: package list missing: $LIST" >&2
    exit 2
fi

# Clean previous generation but leave the parent dir intact.
rm -rf "$DEST_ROOT"
mkdir -p "$DEST_ROOT"

count=0
while IFS= read -r pkg; do
    [[ -z "$pkg" || "${pkg:0:1}" == "#" ]] && continue
    # Convert scoped names to a filesystem-safe slug for the directory:
    # `@babel/core` → `at-babel-core`. Keeps run-audit.sh's path-walk
    # simple (no `@` in the dir name) without losing identity.
    safe="$(echo "$pkg" | sed -e 's|^@|at-|' -e 's|/|-|g')"
    dir="$DEST_ROOT/$safe"
    mkdir -p "$dir"

    # Author the package.json. The `_pkg` field below records the
    # ORIGINAL npm name so `direct_deps()` in run-audit.sh reads the
    # right key — `dependencies` is the canonical key the harness
    # uses, which preserves the original name (with `@scope/`) when
    # we want it.
    cat > "$dir/package.json" <<EOF
{
	"name": "audit-top-npm-$safe",
	"version": "1.0.0",
	"private": true,
	"_comment": "confidence-followup — top-100 npm package install audit. Generated by bench/top-npm-audit/generate.sh; do not hand-edit. Risk shape: long-tail real-world dep declarations of '${pkg}' under both isolated + hoisted layouts. Mode-asymmetric outcomes are regressions.",
	"dependencies": {
		"${pkg}": "latest"
	}
}
EOF

    # Smoke verifies the package loads end-to-end after lpm install.
    # First attempts CJS \`require()\`. We fall back to \`import()\`
    # ONLY when the require failure looks like a genuine ESM-only
    # surface (ERR_REQUIRE_ESM / ERR_REQUIRE_ASYNC_MODULE, or an
    # import-only export map). Ordinary require failures still fail the
    # smoke — otherwise we'd mask real CJS / loader regressions by
    # accepting an unrelated ESM path.
    #
    # Pre-fix this was require-only; ESM-only packages all FAIL/FAIL
    # symmetrically and got filtered as "upstream incompat," which
    # systematically undercovered an increasing share of the long
    # tail (per top-npm-audit/README.md).
    cat > "$dir/smoke.sh" <<EOF
#!/bin/bash
# Auto-generated by bench/top-npm-audit/generate.sh.
# Verifies '${pkg}' loads under the lpm-rendered node_modules layout.
# Tries CJS \`require\` first; falls back to ESM \`import\` only when
# the require failure is genuinely ESM-specific. Ordinary require
# failures still fail the smoke so we don't hide real CJS / loader bugs.
#
    # Bin-only packages (no main + no exports."."/import — e.g.
    # dotenv-cli) genuinely have no programmatic entry point: both
    # require AND import fail. Those still surface as FAIL/FAIL, but the
    # summary now marks them as non-runtime-package instead of lumping
    # them into an anonymous symmetric-failure bucket.
set -e
set +e
node -e "
const fs = require('fs')
const path = require('path')

const packageName = '${pkg}'

function hasCondition(value, condition) {
    if (!value || typeof value !== 'object') {
        return false
    }

    if (Array.isArray(value)) {
        return value.some(entry => hasCondition(entry, condition))
    }

    if (Object.prototype.hasOwnProperty.call(value, condition)) {
        return true
    }

    return Object.values(value).some(entry => hasCondition(entry, condition))
}

function hasImportOnlyExports() {
    try {
        const packageJsonPath = path.join(
            process.cwd(),
            'node_modules',
            ...packageName.split('/'),
            'package.json',
        )
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'))
        const exportsField = packageJson.exports

        if (!exportsField || typeof exportsField !== 'object' || Array.isArray(exportsField)) {
            return false
        }

        return !hasCondition(exportsField, 'require') && hasCondition(exportsField, 'import')
    } catch {
        return false
    }
}

try {
    require(packageName)
    console.log('${pkg}: require ok')
    process.exit(0)
} catch (error) {
    const code = error && error.code
    const message = String((error && error.message) || '')
    const looksEsmOnly =
        code === 'ERR_REQUIRE_ESM' ||
        code === 'ERR_REQUIRE_ASYNC_MODULE' ||
        message.includes('require() of ES Module') ||
        hasImportOnlyExports()

    if (looksEsmOnly) {
        process.exit(42)
    }

    console.error(error && error.stack ? error.stack : String(error))
    process.exit(1)
}
"
status=\$?
set -e

if [[ \$status -eq 0 ]]; then
        exit 0
fi

if [[ \$status -ne 42 ]]; then
    exit "\$status"
fi

node --input-type=module -e "await import('${pkg}')"
echo '${pkg}: import ok'
EOF
    chmod +x "$dir/smoke.sh"

    # README explains why the fixture exists for future readers.
    cat > "$dir/README.md" <<EOF
# top-npm/$safe

Auto-generated single-dep fixture for **${pkg}** (). Tests
that the package installs cleanly under both isolated and hoisted
modes, and that its shipped programmatic entry point resolves under
the lpm-rendered \`node_modules\` layout.

This file is auto-generated. To regenerate after editing the top-N
list:

\`\`\`bash
bash bench/top-npm-audit/generate.sh
\`\`\`
EOF

    count=$((count+1))
done < "$LIST"

echo "[generate] produced $count fixtures under $DEST_ROOT"
