#!/bin/bash
# Generate one top-N fixture per package in top-100.txt.
# confidence-followup Most generated fixtures stay single-dep, but a
# small number use a different fixture class when the package's real
# consumer contract is not "load the package root in an otherwise empty
# project" (CLI-only, types-only, runner/tooling, peer-shaped).
#
# The generated fixtures live under
# `bench/audit-fixtures/top-npm/<safe-pkg-name>/` so the existing
# `run-audit.sh` harness can drive them without modification — the
# only difference vs the curated audit-fixtures bucket is volume
# (100+ fixtures vs 28) and the workflow_dispatch-only CI gating.
#
# Output dir is gitignored. Re-running this script overwrites the
# previous generation; lockfiles in cache/store stay out of scope.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
LIST="$HERE/top-100.txt"
DEST_ROOT="$HERE/../audit-fixtures/top-npm"

if [[ ! -f "$LIST" ]]; then
    echo "ERROR: package list missing: $LIST" >&2
    exit 2
fi

# Clean previous generation but leave the parent dir intact.
rm -rf "$DEST_ROOT"
mkdir -p "$DEST_ROOT"

fixture_class() {
    case "$1" in
        "@types/node") echo "types-node" ;;
        "dotenv-cli") echo "cli-bin" ;;
        "vitest") echo "runner-vitest" ;;
        "zustand") echo "peer-react" ;;
        *) echo "runtime-entry" ;;
    esac
}

fixture_class_description() {
    case "$1" in
        "types-node")
            echo "Type-only fixture: compile a tiny TypeScript program instead of loading a runtime entrypoint."
            ;;
        "cli-bin")
            echo "CLI fixture: invoke the package's installed bin instead of treating the package root as a library API."
            ;;
        "runner-vitest")
            echo "Runner fixture: execute a minimal Vitest test file instead of importing the package root in a blank project."
            ;;
        "peer-react")
            echo "Peer-aware fixture: add the React peer so the package root is exercised in a valid consumer shape."
            ;;
        *)
            echo "Default runtime fixture: require the package root first, then fall back to import only for genuine ESM-only surfaces."
            ;;
    esac
}

write_package_json() {
    local pkg="$1"
    local safe="$2"
    local shape="$3"
    local dir="$4"

    PKG="$pkg" SAFE="$safe" SHAPE="$shape" python3 - <<'EOF' > "$dir/package.json"
import json
import os

pkg = os.environ["PKG"]
safe = os.environ["SAFE"]
shape = os.environ["SHAPE"]

dependencies = {pkg: "latest"}
dev_dependencies = {}
comment_suffix = (
    "Uses the default root-load smoke (require first, import fallback for genuine ESM-only surfaces)."
)

if shape == "types-node":
    dev_dependencies["typescript"] = "latest"
    comment_suffix = "Uses a TypeScript compile smoke because the package ships types, not a runtime entrypoint."
elif shape == "cli-bin":
    comment_suffix = "Uses a CLI smoke because the package is consumed via its executable surface."
elif shape == "runner-vitest":
    comment_suffix = "Uses a minimal Vitest run because the package is consumed as a test runner."
elif shape == "peer-react":
    dependencies["react"] = "latest"
    comment_suffix = "Adds the React peer because the package root expects a React-backed consumer shape."

doc = {
    "name": f"audit-top-npm-{safe}",
    "version": "1.0.0",
    "private": True,
    "_comment": (
        "confidence-followup — top-100 npm package install audit. Generated by "
        "bench/top-npm-audit/generate.sh; do not hand-edit. Risk shape: long-tail "
        f"real-world dep declarations of '{pkg}' under both isolated + hoisted layouts. "
        f"{comment_suffix} Mode-asymmetric outcomes are regressions."
    ),
    "dependencies": dependencies,
}

if dev_dependencies:
    doc["devDependencies"] = dev_dependencies

print(json.dumps(doc, indent=2))
EOF
}

write_runtime_smoke() {
    local pkg="$1"
    local dir="$2"

    cat > "$dir/smoke.sh" <<EOF
#!/bin/bash
# Auto-generated by bench/top-npm-audit/generate.sh.
# Verifies '${pkg}' loads under the lpm-rendered node_modules layout.
# Tries CJS \
# \
require\
# first; falls back to ESM \
# \
import\
# only when the require failure is genuinely ESM-specific. Ordinary require
# failures still fail the smoke so we don't hide real CJS / loader bugs.
set -e
set +e
node -e "
const fs = require('fs')
const path = require('path')

const packageName = '${pkg}'

function hasCondition(value, condition) {
    if (!value || typeof value !== 'object') {
        return false
    }

    if (Array.isArray(value)) {
        return value.some(entry => hasCondition(entry, condition))
    }

    if (Object.prototype.hasOwnProperty.call(value, condition)) {
        return true
    }

    return Object.values(value).some(entry => hasCondition(entry, condition))
}

function hasImportOnlyExports() {
    try {
        const packageJsonPath = path.join(
            process.cwd(),
            'node_modules',
            ...packageName.split('/'),
            'package.json',
        )
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'))
        const exportsField = packageJson.exports

        if (!exportsField || typeof exportsField !== 'object' || Array.isArray(exportsField)) {
            return false
        }

        return !hasCondition(exportsField, 'require') && hasCondition(exportsField, 'import')
    } catch {
        return false
    }
}

try {
    require(packageName)
    console.log('${pkg}: require ok')
    process.exit(0)
} catch (error) {
    const code = error && error.code
    const message = String((error && error.message) || '')
    const looksEsmOnly =
        code === 'ERR_REQUIRE_ESM' ||
        code === 'ERR_REQUIRE_ASYNC_MODULE' ||
        message.includes('require() of ES Module') ||
        hasImportOnlyExports()

    if (looksEsmOnly) {
        process.exit(42)
    }

    console.error(error && error.stack ? error.stack : String(error))
    process.exit(1)
}
"
status=\$?
set -e

if [[ \$status -eq 0 ]]; then
    exit 0
fi

if [[ \$status -ne 42 ]]; then
    exit "\$status"
fi

node --input-type=module -e "await import('${pkg}')"
echo '${pkg}: import ok'
EOF
}

write_cli_smoke() {
    local pkg="$1"
    local dir="$2"

    cat > "$dir/smoke.sh" <<EOF
#!/bin/bash
# Auto-generated by bench/top-npm-audit/generate.sh.
# Verifies '${pkg}' through its installed CLI entrypoint.
set -euo pipefail

bin_name=\$(node - <<'NODE'
const packageJson = require('./node_modules/${pkg}/package.json')
const bin = packageJson.bin
if (typeof bin === 'string') {
  const name = packageJson.name.startsWith('@')
    ? packageJson.name.split('/')[1]
    : packageJson.name
  console.log(name)
  process.exit(0)
}
if (bin && typeof bin === 'object') {
  const keys = Object.keys(bin)
  if (keys.length > 0) {
    console.log(keys[0])
    process.exit(0)
  }
}
throw new Error('package does not declare a CLI bin')
NODE
)

if [[ ! -x "node_modules/.bin/\$bin_name" ]]; then
    echo "ERROR: CLI bin missing: node_modules/.bin/\$bin_name" >&2
    exit 1
fi

if "node_modules/.bin/\$bin_name" --help >/tmp/lpm-top-npm-cli.out 2>&1; then
    cat /tmp/lpm-top-npm-cli.out
    exit 0
fi

"node_modules/.bin/\$bin_name" --version
EOF
}

write_types_node_support() {
    local dir="$1"

    cat > "$dir/tsconfig.json" <<'EOF'
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES2020",
    "strict": true,
    "noEmit": true,
    "types": ["node"]
  },
  "files": ["smoke.ts"]
}
EOF

    cat > "$dir/smoke.ts" <<'EOF'
const env: NodeJS.ProcessEnv = process.env;

if (typeof env.PATH !== 'string' && typeof env.PATH !== 'undefined') {
  throw new Error('PATH should be string or undefined');
}
EOF

    cat > "$dir/smoke.sh" <<'EOF'
#!/bin/bash
# Auto-generated by bench/top-npm-audit/generate.sh.
# Verifies the package's type surface via a minimal TypeScript compile.
set -euo pipefail
npx --no-install tsc --pretty false -p tsconfig.json
EOF
}

write_vitest_support() {
    local dir="$1"

    cat > "$dir/smoke.test.mjs" <<'EOF'
import { describe, expect, it } from 'vitest';

describe('vitest smoke', () => {
  it('runs a minimal test file', () => {
    expect(1 + 1).toBe(2);
  });
});
EOF

    cat > "$dir/smoke.sh" <<'EOF'
#!/bin/bash
# Auto-generated by bench/top-npm-audit/generate.sh.
# Verifies the package via a minimal Vitest run.
set -euo pipefail
npx --no-install vitest run smoke.test.mjs --reporter dot
EOF
}

write_fixture_files() {
    local pkg="$1"
    local dir="$2"
    local shape="$3"

    case "$shape" in
        "cli-bin")
            write_cli_smoke "$pkg" "$dir"
            ;;
        "types-node")
            write_types_node_support "$dir"
            ;;
        "runner-vitest")
            write_vitest_support "$dir"
            ;;
        *)
            write_runtime_smoke "$pkg" "$dir"
            ;;
    esac
}

count=0
while IFS= read -r pkg; do
    [[ -z "$pkg" || "${pkg:0:1}" == "#" ]] && continue
    # Convert scoped names to a filesystem-safe slug for the directory:
    # `@babel/core` → `at-babel-core`. Keeps run-audit.sh's path-walk
    # simple (no `@` in the dir name) without losing identity.
    safe="$(echo "$pkg" | sed -e 's|^@|at-|' -e 's|/|-|g')"
    dir="$DEST_ROOT/$safe"
    shape="$(fixture_class "$pkg")"
    class_description="$(fixture_class_description "$shape")"
    mkdir -p "$dir"

    write_package_json "$pkg" "$safe" "$shape" "$dir"
    write_fixture_files "$pkg" "$dir" "$shape"
    chmod +x "$dir/smoke.sh"

    # README explains why the fixture exists for future readers.
    cat > "$dir/README.md" <<EOF
# top-npm/$safe

Auto-generated fixture for **${pkg}**. Tests that the package installs
cleanly under both isolated and hoisted modes using the consumer shape
that best matches the package surface.

Fixture class: **${shape}**

${class_description}

This file is auto-generated. To regenerate after editing the top-N
list:

\`\`\`bash
bash bench/top-npm-audit/generate.sh
\`\`\`
EOF

    count=$((count+1))
done < "$LIST"

echo "[generate] produced $count fixtures under $DEST_ROOT"
