#!/bin/bash
# Generate one single-dep fixture per package in top-100.txt.
# Phase 66 confidence-followup §1b. Each generated fixture is a
# `package.json` with a single dependency at `latest` plus a `smoke.sh`
# that delegates to the audit-fixtures-style require() check.
#
# The generated fixtures live under
# `bench/audit-fixtures/top-npm/<safe-pkg-name>/` so the existing
# `run-audit.sh` harness can drive them without modification — the
# only difference vs the curated audit-fixtures bucket is volume
# (100+ fixtures vs 28) and the workflow_dispatch-only CI gating.
#
# Output dir is gitignored. Re-running this script overwrites the
# previous generation; lockfiles in cache/store stay out of scope.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
LIST="$HERE/top-100.txt"
DEST_ROOT="$HERE/../audit-fixtures/top-npm"

if [[ ! -f "$LIST" ]]; then
    echo "ERROR: package list missing: $LIST" >&2
    exit 2
fi

# Clean previous generation but leave the parent dir intact.
rm -rf "$DEST_ROOT"
mkdir -p "$DEST_ROOT"

count=0
while IFS= read -r pkg; do
    [[ -z "$pkg" || "${pkg:0:1}" == "#" ]] && continue
    # Convert scoped names to a filesystem-safe slug for the directory:
    # `@babel/core` → `at-babel-core`. Keeps run-audit.sh's path-walk
    # simple (no `@` in the dir name) without losing identity.
    safe="$(echo "$pkg" | sed -e 's|^@|at-|' -e 's|/|-|g')"
    dir="$DEST_ROOT/$safe"
    mkdir -p "$dir"

    # Author the package.json. The `_pkg` field below records the
    # ORIGINAL npm name so `direct_deps()` in run-audit.sh reads the
    # right key — `dependencies` is the canonical key the harness
    # uses, which preserves the original name (with `@scope/`) when
    # we want it.
    cat > "$dir/package.json" <<EOF
{
	"name": "audit-top-npm-$safe",
	"version": "1.0.0",
	"private": true,
	"_comment": "Phase 66 confidence-followup §1b — top-100 npm package install audit. Generated by bench/top-npm-audit/generate.sh; do not hand-edit. Risk shape: long-tail real-world dep declarations of '${pkg}' under both isolated + hoisted layouts. Mode-asymmetric outcomes are regressions.",
	"dependencies": {
		"${pkg}": "latest"
	}
}
EOF

    # Smoke verifies the package loads end-to-end after lpm install.
    # First attempts CJS \`require()\`. If the package is ESM-only the
    # require throws ERR_REQUIRE_ESM (or, for packages forcing
    # type=module, MODULE_NOT_FOUND-shaped errors); the fallback runs
    # \`import()\` from a Node ESM scope. Either path satisfying the
    # smoke is enough — we're testing that the package's *shipped
    # entry point* resolves under the lpm-rendered \`node_modules\`
    # layout, not which module system it uses.
    #
    # Pre-fix this was require-only; ESM-only packages all FAIL/FAIL
    # symmetrically and got filtered as "upstream incompat," which
    # systematically undercovered an increasing share of the long
    # tail (per top-npm-audit/README.md).
    cat > "$dir/smoke.sh" <<EOF
#!/bin/bash
# Auto-generated by bench/top-npm-audit/generate.sh.
# Verifies '${pkg}' loads under the lpm-rendered node_modules layout.
# Tries CJS \`require\` first; falls back to ESM \`import\` for
# package.json#type=module / exports."." conditions that block require.
# Either path is sufficient — we're testing that the package's shipped
# entry point resolves, not which module system it ships.
#
# Bin-only packages (no main + no exports."."/import — e.g.
# dotenv-cli) genuinely have no programmatic entry point: both
# require AND import fail. Those still surface as FAIL/FAIL — that's
# the correct signal ("this top-N package has no API to smoke
# against") and remains symmetric across linker modes.
set -e
if node -e "require('${pkg}')" 2>/dev/null; then
    echo '${pkg}: require ok'
    exit 0
fi
node --input-type=module -e "await import('${pkg}')"
echo '${pkg}: import ok'
EOF
    chmod +x "$dir/smoke.sh"

    # README explains why the fixture exists for future readers.
    cat > "$dir/README.md" <<EOF
# top-npm/$safe

Auto-generated single-dep fixture for **${pkg}** (Phase 66 §1b). Tests
that the package installs cleanly under both isolated and hoisted
modes, and that \`require('${pkg}')\` resolves successfully.

This file is auto-generated. To regenerate after editing the top-N
list:

\`\`\`bash
bash bench/top-npm-audit/generate.sh
\`\`\`
EOF

    count=$((count+1))
done < "$LIST"

echo "[generate] produced $count fixtures under $DEST_ROOT"
