use crate::install_ui;
use lpm_common::LpmError;
use lpm_registry::RegistryClient;
use serde::Deserialize;
use std::path::Path;

const GENERATED_HEADER: &str = "# LPM Registry (generated by lpm setup local — do not commit)";
const CI_GENERATED_HEADER: &str = "# LPM Registry (generated by lpm setup ci npmrc)";
const GENERATED_END: &str = "# End LPM Registry";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct TokenCreateResponse {
    token: String,
    scope: String,
    expires_at: String,
}

/// Generate a read-only .npmrc token for local development.
///
/// Creates a scoped read-only token and writes it to the project's .npmrc.
/// Also ensures .npmrc is in .gitignore to prevent accidental commits.
///
/// Default: scoped config (`@lpm.dev:registry=`) — only LPM packages go through lpm.dev.
pub async fn run(
    client: &RegistryClient,
    project_dir: &Path,
    registry_url: &str,
    days: u32,
    json_output: bool,
) -> Result<(), LpmError> {
    if !(1..=90).contains(&days) {
        return Err(LpmError::Script(
            "--days must be between 1 and 90".to_string(),
        ));
    }

    let pkg_json_path = project_dir.join("package.json");
    let npmrc_path = project_dir.join(".npmrc");
    let gitignore_path = project_dir.join(".gitignore");

    let package_json_content = match lpm_common::read_text_file_capped(
        &pkg_json_path,
        lpm_common::CONFIG_FILE_SIZE_CAP_BYTES,
    ) {
        Ok(content) => Some(content),
        Err(lpm_common::BoundedReadError::NotFound { .. }) => None,
        Err(error) => return Err(error.into()),
    };
    let existing_npmrc =
        match lpm_common::read_text_file_capped(&npmrc_path, lpm_common::NPMRC_FILE_SIZE_CAP_BYTES)
        {
            Ok(content) => content,
            Err(lpm_common::BoundedReadError::NotFound { .. }) => String::new(),
            Err(error) => return Err(error.into()),
        };
    let existing_gitignore = match lpm_common::read_text_file_capped(
        &gitignore_path,
        lpm_common::CONFIG_FILE_SIZE_CAP_BYTES,
    ) {
        Ok(content) => Some(content),
        Err(lpm_common::BoundedReadError::NotFound { .. }) => None,
        Err(error) => return Err(error.into()),
    };

    if package_json_content.is_none() && !json_output {
        install_ui::warn("No package.json found. Run this command in your project root.");
    }

    // Derive project name for the token label
    let project_name = if let Some(content) = package_json_content {
        serde_json::from_str::<serde_json::Value>(&content)
            .ok()
            .and_then(|v| v.get("name")?.as_str().map(|s| s.to_string()))
            .map_or_else(
                || "project".to_string(),
                |name| {
                    name.chars()
                        .map(|c| {
                            if c.is_alphanumeric() || c == '.' || c == '-' || c == '_' {
                                c
                            } else {
                                '-'
                            }
                        })
                        .collect::<String>()
                },
            )
    } else {
        "project".to_string()
    };

    if !json_output {
        install_ui::phase("Creating read-only token...");
    }

    // Create scoped read-only token via API
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|error| LpmError::Script(format!("system clock is before Unix epoch: {error}")))?
        .as_secs();
    // Simple date: days since epoch → YYYY-MM-DD
    let days_since_epoch = now / 86400;
    let today = format!("{}", days_since_epoch); // Use epoch days as unique suffix
    let token_name = format!("npmrc-{project_name}-{today}");

    let body = serde_json::json!({
        "scope": "read",
        "name": token_name,
        "expiryDays": days,
    });

    let url = format!("{registry_url}/api/registry/-/token/create");
    let response = client
        .post_json_raw(&url, &body)
        .await
        .map_err(|e| LpmError::Registry(format!("failed to create token: {e}")))?;

    if !response.status().is_success() {
        let status = response.status();
        let error: serde_json::Value =
            lpm_registry::parse_capped_api_json(response, "project token error").await?;
        let message = error
            .get("error")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("project token creation failed");
        let message = lpm_common::sanitize_terminal_inline(message);
        return Err(LpmError::Registry(format!("{message} ({status})")));
    }
    let created: TokenCreateResponse =
        lpm_registry::parse_capped_api_json(response, "project token response").await?;
    let token_is_safe = created.token.starts_with("lpm_")
        && created
            .token
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'));
    if !token_is_safe
        || created.scope != "read"
        || chrono::DateTime::parse_from_rfc3339(&created.expires_at).is_err()
    {
        return Err(LpmError::Registry(
            "invalid project token response: expected a read-only token and expiry".into(),
        ));
    }
    let read_token = created.token;
    let expires_at = created.expires_at;

    if !json_output {
        install_ui::done("Read-only token created.");
    }

    // Build .npmrc content
    let full_registry_url = if registry_url.ends_with("/api/registry") {
        registry_url.to_string()
    } else {
        format!("{registry_url}/api/registry")
    };
    let registry_host = full_registry_url.replace("https:", "").replace("http:", "");

    if !existing_npmrc.is_empty() {
        let has_custom_registry = existing_npmrc.lines().any(|line| {
            line.starts_with("registry=")
                && !line.contains("registry.npmjs.org")
                && !line.contains("lpm.dev")
        });
        if has_custom_registry && !json_output {
            install_ui::phase("Found existing custom default registry. Using scoped mode.");
        }
    }

    let registry_line = format!("@lpm.dev:registry={full_registry_url}");

    let lpm_config = format!(
        "{GENERATED_HEADER}\n{registry_line}\n{registry_host}/:_authToken={read_token}\n{GENERATED_END}"
    );
    let final_content = replace_generated_block(&existing_npmrc, &lpm_config);
    lpm_common::write_file_atomic_with_options(
        &npmrc_path,
        final_content,
        lpm_common::AtomicWriteOptions::new().unix_mode(0o600),
    )?;

    // Ensure .npmrc is in .gitignore
    let mut gitignore_updated = false;
    let current_gitignore = existing_gitignore.unwrap_or_default();
    let mut gitignore_lines: Vec<&str> = current_gitignore
        .lines()
        .filter(|line| line.trim() != ".npmrc")
        .collect();
    gitignore_lines.push(".npmrc");
    let updated_gitignore = format!("{}\n", gitignore_lines.join("\n"));
    if updated_gitignore != current_gitignore {
        lpm_common::write_file_atomic(&gitignore_path, updated_gitignore)?;
        gitignore_updated = true;
    }

    // Output
    if json_output {
        let json = serde_json::json!({
            "success": true,
            "npmrc_path": npmrc_path.display().to_string(),
            "gitignore_path": gitignore_path.display().to_string(),
            "proxy": false,
            "scope": created.scope,
            "expires_at": expires_at,
            "expiry_days": days,
            "gitignore_updated": gitignore_updated,
        });
        let rendered = serde_json::to_string_pretty(&json).map_err(|error| {
            LpmError::Registry(format!("failed to encode JSON output: {error}"))
        })?;
        println!("{rendered}");
    } else {
        install_ui::done(".npmrc configured with read-only LPM token.");
        if gitignore_updated {
            install_ui::phase(".npmrc added to .gitignore to prevent token leaks.");
        }
        install_ui::phase("Only @lpm.dev packages will route through lpm.dev.");
        if !expires_at.is_empty() {
            install_ui::phase_line(crate::install_ui::terminal_line!(
                "{} {} ({})",
                install_ui::dim("Token expires:"),
                expires_at,
                install_ui::yellow(&format_days_label(days))
            ));
        }
        install_ui::phase("Run `lpm setup local` again to refresh when expired.");
    }

    Ok(())
}

fn replace_generated_block(existing: &str, generated: &str) -> String {
    let lines: Vec<_> = existing.lines().collect();
    let mut kept = Vec::with_capacity(lines.len());
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index];
        if is_generated_header(line) {
            let next_boundary = lines[index + 1..]
                .iter()
                .position(|candidate| *candidate == GENERATED_END || is_generated_header(candidate))
                .map(|offset| index + 1 + offset);
            index = match next_boundary {
                Some(end) if lines[end] == GENERATED_END => end + 1,
                _ => (index + 3).min(lines.len()),
            };
            continue;
        }
        kept.push(line);
        index += 1;
    }
    let prefix = kept.join("\n").trim().to_string();
    if prefix.is_empty() {
        format!("{generated}\n")
    } else {
        format!("{prefix}\n\n{generated}\n")
    }
}

fn is_generated_header(line: &str) -> bool {
    line == GENERATED_HEADER || line == CI_GENERATED_HEADER
}

fn format_days_label(days: u32) -> String {
    if days == 1 {
        "1 day".to_string()
    } else {
        format!("{days} days")
    }
}
