use crate::install_ui;
use lpm_common::LpmError;
use lpm_registry::RegistryClient;
use serde::Deserialize;
use std::path::Path;

const GENERATED_HEADER: &str = "# LPM Registry (generated by lpm setup local — do not commit)";
const CI_GENERATED_HEADER: &str = "# LPM Registry (generated by lpm setup ci npmrc)";
const TOKEN_ID_PREFIX: &str = "# LPM project token id: ";
const GENERATED_END: &str = "# End LPM Registry";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct TokenCreateResponse {
    token: String,
    token_id: String,
    scope: String,
    expires_at: String,
}

#[derive(Clone, Copy)]
struct SetupRollback<'a> {
    gitignore_path: &'a Path,
    expected_gitignore: &'a str,
    original_gitignore: Option<&'a str>,
    npmrc: Option<(&'a Path, &'a str, &'a str)>,
}

impl<'a> SetupRollback<'a> {
    fn new(
        gitignore_path: &'a Path,
        expected_gitignore: &'a str,
        original_gitignore: Option<&'a str>,
    ) -> Self {
        Self {
            gitignore_path,
            expected_gitignore,
            original_gitignore,
            npmrc: None,
        }
    }

    fn with_npmrc(
        mut self,
        npmrc_path: &'a Path,
        expected_npmrc: &'a str,
        original_npmrc: &'a str,
    ) -> Self {
        self.npmrc = Some((npmrc_path, expected_npmrc, original_npmrc));
        self
    }

    fn restore(self) -> Vec<String> {
        let mut errors = Vec::with_capacity(2);
        if let Some((npmrc_path, expected_npmrc, original_npmrc)) = self.npmrc
            && let Err(error) = restore_file_if_unchanged(
                npmrc_path,
                expected_npmrc,
                Some(original_npmrc),
                lpm_common::NPMRC_FILE_SIZE_CAP_BYTES,
                true,
            )
        {
            errors.push(format!("failed to restore .npmrc: {error}"));
        }
        if let Err(error) = restore_file_if_unchanged(
            self.gitignore_path,
            self.expected_gitignore,
            self.original_gitignore,
            lpm_common::CONFIG_FILE_SIZE_CAP_BYTES,
            false,
        ) {
            errors.push(format!("failed to restore .gitignore: {error}"));
        }
        errors
    }
}

/// Generate a read-only .npmrc token for local development.
///
/// Creates a scoped read-only token and writes it to the project's .npmrc.
/// Also ensures .npmrc is in .gitignore to prevent accidental commits.
///
/// Default: scoped config (`@lpm.dev:registry=`) — only LPM packages go through lpm.dev.
pub async fn run(
    client: &RegistryClient,
    project_dir: &Path,
    registry_url: &str,
    days: u32,
    json_output: bool,
) -> Result<(), LpmError> {
    if !(1..=90).contains(&days) {
        return Err(LpmError::Script(
            "--days must be between 1 and 90".to_string(),
        ));
    }

    let pkg_json_path = project_dir.join("package.json");
    let npmrc_path = project_dir.join(".npmrc");
    let gitignore_path = project_dir.join(".gitignore");

    let package_json_content = match lpm_common::read_text_file_capped(
        &pkg_json_path,
        lpm_common::CONFIG_FILE_SIZE_CAP_BYTES,
    ) {
        Ok(content) => Some(content),
        Err(lpm_common::BoundedReadError::NotFound { .. }) => None,
        Err(error) => return Err(error.into()),
    };
    let existing_npmrc =
        match lpm_common::read_text_file_capped(&npmrc_path, lpm_common::NPMRC_FILE_SIZE_CAP_BYTES)
        {
            Ok(content) => content,
            Err(lpm_common::BoundedReadError::NotFound { .. }) => String::new(),
            Err(error) => return Err(error.into()),
        };
    let existing_gitignore = match lpm_common::read_text_file_capped(
        &gitignore_path,
        lpm_common::CONFIG_FILE_SIZE_CAP_BYTES,
    ) {
        Ok(content) => Some(content),
        Err(lpm_common::BoundedReadError::NotFound { .. }) => None,
        Err(error) => return Err(error.into()),
    };

    if package_json_content.is_none() && !json_output {
        install_ui::warn("No package.json found. Run this command in your project root.");
    }

    let project_name = if let Some(content) = package_json_content {
        serde_json::from_str::<serde_json::Value>(&content)
            .ok()
            .and_then(|v| v.get("name")?.as_str().map(|s| s.to_string()))
            .map_or_else(
                || "project".to_string(),
                |name| {
                    name.chars()
                        .map(|c| {
                            if c.is_alphanumeric() || c == '.' || c == '-' || c == '_' {
                                c
                            } else {
                                '-'
                            }
                        })
                        .collect::<String>()
                },
            )
    } else {
        "project".to_string()
    };

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|error| LpmError::Script(format!("system clock is before Unix epoch: {error}")))?
        .as_secs();
    let days_since_epoch = now / 86400;
    let today = format!("{days_since_epoch}");
    let token_name = format!("npmrc-{project_name}-{today}");
    let body = serde_json::json!({
        "scope": "read",
        "name": token_name,
        "expiryDays": days,
    });

    let full_registry_url = if registry_url.ends_with("/api/registry") {
        registry_url.to_string()
    } else {
        format!("{registry_url}/api/registry")
    };
    let registry_host = full_registry_url.replace("https:", "").replace("http:", "");
    let registry_line = format!("@lpm.dev:registry={full_registry_url}");
    let old_token_id = generated_token_id(&existing_npmrc);

    if !existing_npmrc.is_empty() {
        let has_custom_registry = existing_npmrc.lines().any(|line| {
            line.starts_with("registry=")
                && !line.contains("registry.npmjs.org")
                && !line.contains("lpm.dev")
        });
        if has_custom_registry && !json_output {
            install_ui::phase("Found existing custom default registry. Using scoped mode.");
        }
    }

    let current_gitignore = existing_gitignore.as_deref().unwrap_or_default();
    let mut gitignore_lines: Vec<&str> = current_gitignore
        .lines()
        .filter(|line| line.trim() != ".npmrc")
        .collect();
    gitignore_lines.push(".npmrc");
    let updated_gitignore = format!("{}\n", gitignore_lines.join("\n"));
    let gitignore_updated = updated_gitignore != current_gitignore;
    let rollback = SetupRollback::new(
        &gitignore_path,
        &updated_gitignore,
        existing_gitignore.as_deref(),
    );
    if gitignore_updated {
        lpm_common::write_file_atomic(&gitignore_path, &updated_gitignore)?;
    }

    if !json_output {
        install_ui::phase("Creating read-only token...");
    }

    let url = format!(
        "{}/api/registry/-/token/create",
        registry_url.trim_end_matches('/')
    );
    let response = match client.post_json_raw(&url, &body).await {
        Ok(response) => response,
        Err(error) => {
            let primary = LpmError::Registry(format!("failed to create token: {error}"));
            return Err(rollback_without_token(primary, rollback));
        }
    };

    if !response.status().is_success() {
        let status = response.status();
        let error: serde_json::Value =
            match lpm_registry::parse_capped_api_json(response, "project token error").await {
                Ok(error) => error,
                Err(error) => {
                    return Err(rollback_without_token(error, rollback));
                }
            };
        let message = error
            .get("error")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("project token creation failed");
        let message = lpm_common::sanitize_terminal_inline(message);
        return Err(rollback_without_token(
            LpmError::Registry(format!("{message} ({status})")),
            rollback,
        ));
    }

    let created_value: serde_json::Value =
        match lpm_registry::parse_capped_api_json(response, "project token response").await {
            Ok(value) => value,
            Err(error) => {
                return Err(rollback_without_token(error, rollback));
            }
        };
    let rollback_token_id = created_value
        .get("tokenId")
        .and_then(serde_json::Value::as_str)
        .filter(|token_id| valid_token_id(token_id))
        .map(str::to_string);
    let created: TokenCreateResponse = match serde_json::from_value(created_value) {
        Ok(created) => created,
        Err(error) => {
            let primary = LpmError::Registry(format!("invalid project token response: {error}"));
            return Err(rollback_created_token(
                client,
                registry_url,
                rollback_token_id.as_deref(),
                primary,
                rollback,
            )
            .await);
        }
    };
    let token_is_safe = created.token.starts_with("lpm_")
        && created
            .token
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'));
    if !token_is_safe
        || !valid_token_id(&created.token_id)
        || created.scope != "read"
        || chrono::DateTime::parse_from_rfc3339(&created.expires_at).is_err()
    {
        let primary = LpmError::Registry(
            "invalid project token response: expected a read-only token, token ID, and expiry"
                .into(),
        );
        return Err(rollback_created_token(
            client,
            registry_url,
            rollback_token_id.as_deref(),
            primary,
            rollback,
        )
        .await);
    }
    let read_token = created.token;
    let token_id = created.token_id;
    let expires_at = created.expires_at;

    let lpm_config = format!(
        "{GENERATED_HEADER}\n{TOKEN_ID_PREFIX}{token_id}\n{registry_line}\n{registry_host}/:_authToken={read_token}\n{GENERATED_END}"
    );
    let final_content = replace_generated_block(&existing_npmrc, &lpm_config);
    if let Err(error) = lpm_common::write_file_atomic_with_options(
        &npmrc_path,
        &final_content,
        lpm_common::AtomicWriteOptions::new().unix_mode(0o600),
    ) {
        return Err(rollback_created_token(
            client,
            registry_url,
            Some(&token_id),
            LpmError::Io(error),
            rollback,
        )
        .await);
    }

    if let Some(old_token_id) = old_token_id.as_deref()
        && old_token_id != token_id
        && let Err(error) = revoke_project_token(client, registry_url, old_token_id).await
    {
        return Err(rollback_created_token(
            client,
            registry_url,
            Some(&token_id),
            error,
            rollback.with_npmrc(&npmrc_path, &final_content, &existing_npmrc),
        )
        .await);
    }

    if !json_output {
        install_ui::done("Read-only token created.");
    }

    if json_output {
        let json = serde_json::json!({
            "success": true,
            "npmrc_path": npmrc_path.display().to_string(),
            "gitignore_path": gitignore_path.display().to_string(),
            "proxy": false,
            "scope": created.scope,
            "expires_at": expires_at,
            "expiry_days": days,
            "gitignore_updated": gitignore_updated,
        });
        let rendered = serde_json::to_string_pretty(&json).map_err(|error| {
            LpmError::Registry(format!("failed to encode JSON output: {error}"))
        })?;
        println!("{rendered}");
    } else {
        install_ui::done(".npmrc configured with read-only LPM token.");
        if gitignore_updated {
            install_ui::phase(".npmrc added to .gitignore to prevent token leaks.");
        }
        install_ui::phase("Only @lpm.dev packages will route through lpm.dev.");
        if !expires_at.is_empty() {
            install_ui::phase_line(crate::install_ui::terminal_line!(
                "{} {} ({})",
                install_ui::dim("Token expires:"),
                expires_at,
                install_ui::yellow(&format_days_label(days))
            ));
        }
        install_ui::phase("Run `lpm setup local` again to refresh when expired.");
    }

    Ok(())
}

fn rollback_without_token(primary: LpmError, rollback: SetupRollback<'_>) -> LpmError {
    combine_rollback_error(primary, rollback.restore())
}

async fn rollback_created_token(
    client: &RegistryClient,
    registry_url: &str,
    token_id: Option<&str>,
    primary: LpmError,
    rollback: SetupRollback<'_>,
) -> LpmError {
    let mut rollback_errors = Vec::with_capacity(3);
    if let Some(token_id) = token_id
        && let Err(error) = revoke_project_token(client, registry_url, token_id).await
    {
        rollback_errors.push(format!("failed to revoke replacement token: {error}"));
    }
    rollback_errors.extend(rollback.restore());
    combine_rollback_error(primary, rollback_errors)
}

fn restore_file_if_unchanged(
    path: &Path,
    expected_current: &str,
    original: Option<&str>,
    cap: u64,
    sensitive: bool,
) -> Result<(), String> {
    let current = match lpm_common::read_text_file_capped(path, cap) {
        Ok(current) => Some(current),
        Err(lpm_common::BoundedReadError::NotFound { .. }) => None,
        Err(error) => return Err(error.to_string()),
    };
    if current.as_deref() == original {
        return Ok(());
    }
    if current.as_deref() != Some(expected_current) {
        return Err(format!(
            "{} changed concurrently; refusing to overwrite it",
            path.display()
        ));
    }

    match original {
        Some(contents) if sensitive => lpm_common::write_file_atomic_with_options(
            path,
            contents,
            lpm_common::AtomicWriteOptions::new().unix_mode(0o600),
        )
        .map_err(|error| error.to_string()),
        Some(contents) => {
            lpm_common::write_file_atomic(path, contents).map_err(|error| error.to_string())
        }
        None => std::fs::remove_file(path).map_err(|error| error.to_string()),
    }
}

fn combine_rollback_error(primary: LpmError, rollback_errors: Vec<String>) -> LpmError {
    if rollback_errors.is_empty() {
        primary
    } else {
        LpmError::Script(format!(
            "{primary}; rollback incomplete: {}",
            rollback_errors.join("; ")
        ))
    }
}

async fn revoke_project_token(
    client: &RegistryClient,
    registry_url: &str,
    token_id: &str,
) -> Result<(), LpmError> {
    let url = format!(
        "{}/api/registry/-/token/revoke-project",
        registry_url.trim_end_matches('/')
    );
    let response = client
        .post_json_raw(&url, &serde_json::json!({ "tokenId": token_id }))
        .await
        .map_err(|error| LpmError::Registry(format!("failed to revoke project token: {error}")))?;
    let status = response.status();
    let body: serde_json::Value =
        lpm_registry::parse_capped_api_json(response, "project token revocation response").await?;
    if !status.is_success() {
        let message = body
            .get("error")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("project token revocation failed");
        return Err(LpmError::Registry(format!(
            "{} ({status})",
            lpm_common::sanitize_terminal_inline(message)
        )));
    }
    if body.get("revoked").and_then(serde_json::Value::as_bool) != Some(true)
        || body.get("tokenId").and_then(serde_json::Value::as_str) != Some(token_id)
    {
        return Err(LpmError::Registry(
            "invalid project token revocation response".into(),
        ));
    }
    Ok(())
}

fn generated_token_id(existing: &str) -> Option<String> {
    let mut in_local_block = false;
    for line in existing.lines() {
        if line == GENERATED_HEADER {
            in_local_block = true;
            continue;
        }
        if !in_local_block {
            continue;
        }
        if line == GENERATED_END || is_generated_header(line) {
            return None;
        }
        if let Some(token_id) = line.strip_prefix(TOKEN_ID_PREFIX) {
            return valid_token_id(token_id).then(|| token_id.to_string());
        }
    }
    None
}

fn valid_token_id(token_id: &str) -> bool {
    let bytes = token_id.as_bytes();
    bytes.len() == 36
        && bytes.iter().enumerate().all(|(index, byte)| {
            if matches!(index, 8 | 13 | 18 | 23) {
                *byte == b'-'
            } else {
                byte.is_ascii_hexdigit()
            }
        })
}

fn replace_generated_block(existing: &str, generated: &str) -> String {
    let lines: Vec<_> = existing.lines().collect();
    let mut kept = Vec::with_capacity(lines.len());
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index];
        if is_generated_header(line) {
            let next_boundary = lines[index + 1..]
                .iter()
                .position(|candidate| *candidate == GENERATED_END || is_generated_header(candidate))
                .map(|offset| index + 1 + offset);
            index = match next_boundary {
                Some(end) if lines[end] == GENERATED_END => end + 1,
                _ => {
                    let generated_line_count = if lines
                        .get(index + 1)
                        .is_some_and(|line| line.starts_with(TOKEN_ID_PREFIX))
                    {
                        4
                    } else {
                        3
                    };
                    (index + generated_line_count).min(lines.len())
                }
            };
            continue;
        }
        kept.push(line);
        index += 1;
    }
    let prefix = kept.join("\n").trim().to_string();
    if prefix.is_empty() {
        format!("{generated}\n")
    } else {
        format!("{prefix}\n\n{generated}\n")
    }
}

fn is_generated_header(line: &str) -> bool {
    line == GENERATED_HEADER || line == CI_GENERATED_HEADER
}

fn format_days_label(days: u32) -> String {
    if days == 1 {
        "1 day".to_string()
    } else {
        format!("{days} days")
    }
}
