use crate::{install_ui, oidc};
use lpm_common::LpmError;
use lpm_common::color::Painted;
use lpm_registry::RegistryClient;
use std::path::Path;

fn hint_line(message: &str) {
    eprintln!("  {}", install_ui::dim(message));
}

const GENERATED_HEADER: &str = "# LPM Registry (generated by lpm setup ci npmrc)";
const LOCAL_GENERATED_HEADER: &str =
    "# LPM Registry (generated by lpm setup local — do not commit)";
const GENERATED_END: &str = "# End LPM Registry";
pub(crate) const DEFAULT_CI_ENVIRONMENT: &str = "production";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CiWorkflowTarget {
    GithubActions,
    Gitlab,
}

impl CiWorkflowTarget {
    fn canonical_name(self) -> &'static str {
        match self {
            Self::GithubActions => "github-actions",
            Self::Gitlab => "gitlab",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CiSetupTarget {
    Npmrc,
    Workflow(CiWorkflowTarget),
}

impl CiSetupTarget {
    pub(crate) fn parse(raw: &str) -> Result<Self, LpmError> {
        match raw {
            "npmrc" => Ok(Self::Npmrc),
            "github-actions" | "github" | "gha" => {
                Ok(Self::Workflow(CiWorkflowTarget::GithubActions))
            }
            "gitlab" | "gitlab-ci" => Ok(Self::Workflow(CiWorkflowTarget::Gitlab)),
            other => Err(LpmError::Script(format!(
                "unknown CI setup target: '{other}'. Available: npmrc, github-actions, gitlab"
            ))),
        }
    }

    fn canonical_name(self) -> &'static str {
        match self {
            Self::Npmrc => "npmrc",
            Self::Workflow(platform) => platform.canonical_name(),
        }
    }
}

pub(crate) fn validate_ci_flags(
    target: CiSetupTarget,
    env_requested: bool,
    registry_requested: bool,
    oidc_requested: bool,
) -> Result<(), LpmError> {
    match target {
        CiSetupTarget::Npmrc if env_requested => Err(LpmError::Script(
            "`--env` does not apply to `lpm setup ci npmrc`. Use `--env` only with github-actions or gitlab."
                .into(),
        )),
        CiSetupTarget::Workflow(_) => {
            let (invalid_flags, verb, pronoun) = match (registry_requested, oidc_requested) {
                (true, true) => ("`--registry` and `--oidc`", "do", "them"),
                (true, false) => ("`--registry`", "does", "it"),
                (false, true) => ("`--oidc`", "does", "it"),
                (false, false) => return Ok(()),
            };
            Err(LpmError::Script(format!(
                "{invalid_flags} {verb} not apply to `lpm setup ci {}`. Use {pronoun} only with npmrc.",
                target.canonical_name(),
            )))
        }
        _ => Ok(()),
    }
}

async fn resolve_lpm_bearer(
    session: &lpm_auth::SessionManager,
    registry_url: &str,
) -> Result<ResolvedSetupBearer, LpmError> {
    let token = match session
        .bearer_string_for(lpm_auth::AuthRequirement::TokenRequired)
        .await
    {
        Ok(token) => token,
        Err(LpmError::AuthRequired | LpmError::SessionExpired) => {
            return Err(LpmError::Script(
                "no usable bearer is available. Set LPM_TOKEN for this command, or run `lpm login` and retry. LPM CLI can consume LPM_TOKEN directly; `setup ci npmrc` writes a protected literal token for npm-compatible clients."
                    .into(),
            ));
        }
        Err(error) => return Err(error),
    };
    let source = session.current_source()?;
    let storage = match source {
        Some(lpm_auth::TokenSource::StoredSession) => lpm_auth::auth_storage_status(registry_url),
        _ => lpm_auth::AuthStorageStatus::none(),
    };
    Ok(ResolvedSetupBearer {
        token,
        storage,
        uses_env_var: source == Some(lpm_auth::TokenSource::EnvVar),
    })
}

struct ResolvedSetupBearer {
    token: String,
    storage: lpm_auth::AuthStorageStatus,
    uses_env_var: bool,
}

impl ResolvedSetupBearer {
    fn oidc(token: String) -> Self {
        Self {
            token,
            storage: lpm_auth::AuthStorageStatus::none(),
            uses_env_var: false,
        }
    }
}

fn setup_storage_status(token: &ResolvedSetupBearer) -> lpm_auth::AuthStorageStatus {
    token.storage
}

/// Generate .npmrc for CI/CD environments.
///
/// Creates a .npmrc file that configures the LPM registry with auth token
/// so npm/pnpm/yarn can install @lpm.dev packages in CI.
///
/// Default: scoped config (`@lpm.dev:registry=`) — only LPM packages go through lpm.dev.
///
/// Flags:
/// - `--oidc`: Exchange an OIDC token from the CI environment instead of using stored auth.
/// - `--registry` / `-r`: Override the registry URL.
pub async fn run(
    client: &RegistryClient,
    session: &lpm_auth::SessionManager,
    registry_url: &str,
    project_dir: &Path,
    json_output: bool,
    use_oidc: bool,
) -> Result<(), LpmError> {
    let registry = super::npmrc::SetupRegistry::parse(registry_url)?;
    super::npmrc::reject_tracked_npmrc(project_dir)?;

    let npmrc_path = project_dir.join(".npmrc");
    let existing = match lpm_common::read_text_file_capped_nofollow(
        &npmrc_path,
        lpm_common::NPMRC_FILE_SIZE_CAP_BYTES,
    ) {
        Ok(content) => content,
        Err(lpm_common::BoundedReadError::NotFound { .. }) => String::new(),
        Err(error) => return Err(error.into()),
    };
    if let Some(local_registry) = super::npmrc::local_setup_registry_url(&existing)
        && local_registry != registry.endpoint()
    {
        return Err(LpmError::Script(format!(
            "the setup-local token belongs to {local_registry}; rerun with its registry before replacing the generated block"
        )));
    }
    if let Some(ci_registry) = super::npmrc::setup_ci_registry_url(&existing)
        && ci_registry != registry.endpoint()
    {
        return Err(LpmError::Script(format!(
            "the pending CI setup belongs to {ci_registry}; rerun with its registry to finish token retirement safely"
        )));
    }

    let pending_retirement =
        super::npmrc::setup_ci_pending_retirement(&existing, registry.auth_scope())?;
    let token = if let Some((replacement, _)) = pending_retirement.as_ref() {
        ResolvedSetupBearer {
            token: replacement.clone(),
            storage: lpm_auth::AuthStorageStatus::none(),
            uses_env_var: false,
        }
    } else if use_oidc {
        oidc::exchange_oidc_token(registry.service_base(), None, "read")
            .await
            .map(|oidc_token| ResolvedSetupBearer::oidc(oidc_token.token))
            .map_err(|error| {
                LpmError::Script(format!(
                    "OIDC token exchange failed; no fallback was used: {error}"
                ))
            })?
    } else {
        resolve_lpm_bearer(session, registry.service_base()).await?
    };

    let storage_status = setup_storage_status(&token);
    if token.token.is_empty()
        || !token.token.bytes().all(|byte| {
            byte.is_ascii_alphanumeric()
                || matches!(byte, b'-' | b'.' | b'_' | b'~' | b'+' | b'/' | b'=')
        })
    {
        return Err(LpmError::Script(
            "the resolved bearer is malformed and cannot be written safely to .npmrc".into(),
        ));
    }

    let registry_line = format!("@lpm.dev:registry={}/", registry.endpoint());

    let clean_generated = format!(
        "{GENERATED_HEADER}\n{}:_authToken={}\n{}\n{GENERATED_END}",
        registry.auth_scope(),
        token.token,
        registry_line
    );
    let predecessor_bearer = pending_retirement
        .as_ref()
        .map(|(_, predecessor)| predecessor.clone())
        .or(super::npmrc::setup_ci_predecessor_bearer(
            &existing,
            registry.auth_scope(),
        )?);
    let mut staged_content = None;
    if let Some(predecessor_bearer) = predecessor_bearer.as_deref() {
        if predecessor_bearer == token.token {
            return Err(LpmError::Script(
                "setup ci cannot replace a setup-local token with the same bearer because retiring it would make the generated credential unusable. Supply a different bearer through LPM_TOKEN, a stored session, or --oidc"
                    .into(),
            ));
        }
        let pending_content = if pending_retirement.is_some() {
            existing.clone()
        } else {
            let pending_generated = format!(
                "{GENERATED_HEADER}\n{}{}\n{}:_authToken={}\n{}\n{GENERATED_END}",
                super::npmrc::CI_RETIRE_BEARER_PREFIX,
                predecessor_bearer,
                registry.auth_scope(),
                token.token,
                registry_line
            );
            let pending_content =
                replace_generated_block(&existing, &pending_generated, registry.auth_scope());
            lpm_common::write_file_atomic_with_options(
                &npmrc_path,
                &pending_content,
                lpm_common::AtomicWriteOptions::new().unix_mode(0o600),
            )?;
            pending_content
        };
        if let Err(revocation) =
            super::npmrc::self_revoke_project_token(client, &registry, predecessor_bearer).await
        {
            if !revocation.may_have_committed {
                let rollback = super::npmrc::restore_file_if_unchanged(
                    &npmrc_path,
                    &pending_content,
                    Some(&existing),
                    lpm_common::NPMRC_FILE_SIZE_CAP_BYTES,
                    true,
                );
                return match rollback {
                    Ok(()) => Err(revocation.error),
                    Err(rollback_error) => Err(LpmError::Script(format!(
                        "{}; failed to restore .npmrc: {rollback_error}",
                        revocation.error
                    ))),
                };
            }
            return Err(LpmError::Registry(format!(
                "{}. The protected .npmrc contains a usable replacement and retains the predecessor for a safe retry; rerun `lpm setup ci npmrc` with the same registry",
                revocation.error
            )));
        }
        staged_content = Some(pending_content);
    }
    let source_content = staged_content.as_deref().unwrap_or(&existing);
    let npmrc_content =
        replace_generated_block(source_content, &clean_generated, registry.auth_scope());
    lpm_common::write_file_atomic_with_options(
        &npmrc_path,
        &npmrc_content,
        lpm_common::AtomicWriteOptions::new().unix_mode(0o600),
    )?;

    if json_output {
        let safe_content = format!(
            "{GENERATED_HEADER}\n{}:_authToken=<redacted>\n{registry_line}\n{GENERATED_END}\n",
            registry.auth_scope()
        );
        let json = serde_json::json!({
            "success": true,
            "path": npmrc_path.display().to_string(),
            "content": safe_content,
            "uses_env_var": token.uses_env_var,
            "oidc": use_oidc,
            "proxy": false,
            "storage_backend": storage_status.backend_json_value(),
            "storage_degraded": storage_status.degraded,
            "note": "JSON redacts the bearer; the protected on-disk .npmrc contains the runtime-resolved literal token for npm-compatible clients.",
        });
        let rendered = serde_json::to_string_pretty(&json)
            .map_err(|error| LpmError::Script(format!("failed to encode JSON output: {error}")))?;
        println!("{rendered}");
    } else {
        install_ui::done("Generated .npmrc");
        hint_line(&npmrc_path.display().to_string());

        if use_oidc {
            install_ui::phase("Using OIDC-exchanged token.");
        }
        install_ui::phase(
            "The protected file contains a literal bearer for npm-compatible clients; LPM CLI can consume LPM_TOKEN directly.",
        );
    }

    Ok(())
}

fn replace_generated_block(existing: &str, generated: &str, auth_scope: &str) -> String {
    let auth_prefix = format!("{auth_scope}:_authToken=");
    let lines: Vec<_> = existing.lines().collect();
    let mut kept = Vec::with_capacity(lines.len());
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index];
        if is_generated_header(line) {
            let next_boundary = lines[index + 1..]
                .iter()
                .position(|candidate| *candidate == GENERATED_END || is_generated_header(candidate))
                .map(|offset| index + 1 + offset);
            index = match next_boundary {
                Some(end) if lines[end] == GENERATED_END => end + 1,
                _ => {
                    let mut end = index + 1;
                    while lines.get(end).is_some_and(|line| {
                        line.starts_with("# LPM project token id: ")
                            || line.starts_with("# LPM pending project token id: ")
                            || line.starts_with("# LPM previous project token id: ")
                            || line.starts_with("# LPM previous project token hash: ")
                            || line.starts_with("# LPM previous project token bearer: ")
                            || line.starts_with("# LPM pending project token retirement id: ")
                            || line.starts_with("# LPM pending project token retirement hash: ")
                            || line.starts_with(super::npmrc::CI_RETIRE_BEARER_PREFIX)
                            || line.starts_with("@lpm.dev:registry=")
                            || line.contains("/:_authToken=")
                    }) {
                        end += 1;
                    }
                    end
                }
            };
            continue;
        }
        if line.starts_with(&auth_prefix)
            || line.starts_with("@lpm.dev:registry=") && line.contains("/api/registry")
        {
            index += 1;
            continue;
        }
        kept.push(line);
        index += 1;
    }
    let prefix = kept.join("\n").trim().to_string();
    if prefix.is_empty() {
        format!("{generated}\n")
    } else {
        format!("{prefix}\n\n{generated}\n")
    }
}

fn is_generated_header(line: &str) -> bool {
    line == GENERATED_HEADER || line == LOCAL_GENERATED_HEADER
}

pub(crate) fn run_ci_platform(platform: CiWorkflowTarget, project_dir: &Path, env_mode: &str) {
    match platform {
        CiWorkflowTarget::GithubActions => setup_github_actions(project_dir, env_mode),
        CiWorkflowTarget::Gitlab => setup_gitlab_ci(env_mode),
    }
}

fn setup_github_actions(project_dir: &Path, env_mode: &str) {
    let vault_id = lpm_vault::vault_id::read_vault_id(project_dir)
        .unwrap_or_else(|| "<your-vault-id>".to_string());
    let env_mode = install_ui::field(env_mode);
    let vault_id = install_ui::field(&vault_id);

    println!();
    println!("  {} GitHub Actions OIDC Setup", "▸".bold());
    println!();
    println!(
        "  {} Add this to your workflow (.github/workflows/deploy.yml):",
        "1.".bold()
    );
    println!();
    println!(
        "  {}",
        "jobs:
    deploy:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: Install LPM
          run: npm install -g @lpm-registry/cli
        - name: Load secrets from env
          run: lpm env pull --oidc --env={ENV} --output=.env
          env:
            LPM_VAULT_ID: {VAULT_ID}
            LPM_OIDC_POLICY_ID: ${{ vars.LPM_OIDC_POLICY_ID }}
        - name: Deploy
          run: lpm run deploy"
            .replace("{ENV}", env_mode.as_ref())
            .replace("{VAULT_ID}", vault_id.as_ref())
            .dimmed()
    );
    println!();
    println!("  {} Authorize this repo:", "2.".bold());
    println!();
    println!(
        "  {}",
        format!(
            "lpm env oidc allow --provider=github --repo=<owner/repo> \
             --workflow=.github/workflows/deploy.yml --branch=main --env={env_mode}"
        )
        .bold()
    );
    println!();
    println!(
        "  {} Store the policy ID returned by `lpm env oidc allow` as the {} repository variable.",
        "3.".bold(),
        "LPM_OIDC_POLICY_ID".bold(),
    );
    println!();
}

fn setup_gitlab_ci(env_mode: &str) {
    let env_mode = install_ui::field(env_mode);

    println!();
    println!("  {} GitLab CI OIDC Setup", "▸".bold());
    println!();
    println!("  {} Add this to .gitlab-ci.yml:", "1.".bold());
    println!();
    println!(
        "  {}",
        "deploy:
  id_tokens:
    LPM_OIDC_TOKEN:
      aud: https://lpm.dev
  script:
    - npm install -g @lpm-registry/cli
    - lpm env pull --oidc --env={ENV} --output=.env
    - lpm run deploy"
            .replace("{ENV}", env_mode.as_ref())
            .dimmed()
    );
    println!();
    println!("  {} Authorize this project:", "2.".bold());
    println!();
    println!(
        "  {}",
        format!(
            "lpm env oidc allow --provider=gitlab --project-id=<numeric-project-id> --branch=main --env={env_mode}"
        )
        .bold()
    );
    println!();
    println!(
        "  {} Store the policy ID returned by `lpm env oidc allow` as an {} CI/CD variable. Mark it protected only when every allowed ref is protected.",
        "3.".bold(),
        "LPM_OIDC_POLICY_ID".bold(),
    );
    println!();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ci_setup_target_normalizes_workflow_aliases() {
        for (raw, expected) in [
            ("github-actions", CiWorkflowTarget::GithubActions),
            ("github", CiWorkflowTarget::GithubActions),
            ("gha", CiWorkflowTarget::GithubActions),
            ("gitlab", CiWorkflowTarget::Gitlab),
            ("gitlab-ci", CiWorkflowTarget::Gitlab),
        ] {
            assert_eq!(
                CiSetupTarget::parse(raw).expect("known CI setup target must parse"),
                CiSetupTarget::Workflow(expected)
            );
        }
    }

    #[test]
    fn ci_setup_npmrc_rejects_explicit_env() {
        let error = validate_ci_flags(CiSetupTarget::Npmrc, true, false, false).unwrap_err();
        assert!(error.to_string().contains("--env"));
    }

    #[test]
    fn ci_setup_workflow_rejects_registry_and_oidc_together() {
        let target = CiSetupTarget::Workflow(CiWorkflowTarget::GithubActions);
        let error = validate_ci_flags(target, false, true, true).unwrap_err();
        assert!(error.to_string().contains("--registry") && error.to_string().contains("--oidc"));
    }

    #[test]
    fn ci_setup_targets_accept_only_their_supported_flags() {
        assert!(validate_ci_flags(CiSetupTarget::Npmrc, false, true, true).is_ok());
        assert!(
            validate_ci_flags(
                CiSetupTarget::Workflow(CiWorkflowTarget::Gitlab),
                true,
                false,
                false,
            )
            .is_ok()
        );
    }
}
