use crate::{auth_storage_notice, install_ui, oidc};
use lpm_common::LpmError;
use lpm_common::color::Painted;
use lpm_registry::RegistryClient;
use std::path::Path;

fn hint_line(message: &str) {
    eprintln!("  {}", install_ui::dim(message));
}

const GENERATED_HEADER: &str = "# LPM Registry (generated by lpm setup ci npmrc)";
const LOCAL_GENERATED_HEADER: &str =
    "# LPM Registry (generated by lpm setup local — do not commit)";
const GENERATED_END: &str = "# End LPM Registry";

async fn resolve_lpm_bearer(
    registry_url: &str,
    json_output: bool,
) -> Result<ResolvedSetupBearer, LpmError> {
    let session = auth_storage_notice::attach(
        lpm_auth::SessionManager::new(registry_url, None),
        json_output,
    );
    let token = session
        .bearer_string_for(lpm_auth::AuthRequirement::TokenRequired)
        .await
        .map_err(|_| {
            LpmError::Script(
                "no usable bearer is available. Set LPM_TOKEN for this command, or run `lpm login` and retry. LPM CLI can consume LPM_TOKEN directly; `setup ci npmrc` writes a protected literal token for npm-compatible clients."
                    .into(),
            )
        })?;
    let source = session.current_source();
    let storage = match source {
        Some(lpm_auth::TokenSource::StoredSession | lpm_auth::TokenSource::StoredLegacy) => {
            lpm_auth::auth_storage_status(registry_url)
        }
        _ => lpm_auth::AuthStorageStatus::none(),
    };
    Ok(ResolvedSetupBearer {
        token,
        storage,
        uses_env_var: source == Some(lpm_auth::TokenSource::EnvVar),
    })
}

struct ResolvedSetupBearer {
    token: String,
    storage: lpm_auth::AuthStorageStatus,
    uses_env_var: bool,
}

impl ResolvedSetupBearer {
    fn oidc(token: String) -> Self {
        Self {
            token,
            storage: lpm_auth::AuthStorageStatus::none(),
            uses_env_var: false,
        }
    }
}

fn setup_storage_status(token: &ResolvedSetupBearer) -> lpm_auth::AuthStorageStatus {
    token.storage
}

/// Generate .npmrc for CI/CD environments.
///
/// Creates a .npmrc file that configures the LPM registry with auth token
/// so npm/pnpm/yarn can install @lpm.dev packages in CI.
///
/// Default: scoped config (`@lpm.dev:registry=`) — only LPM packages go through lpm.dev.
///
/// Flags:
/// - `--oidc`: Exchange an OIDC token from the CI environment instead of using stored auth.
/// - `--registry` / `-r`: Override the registry URL.
pub async fn run(
    client: &RegistryClient,
    registry_url: &str,
    project_dir: &Path,
    json_output: bool,
    use_oidc: bool,
) -> Result<(), LpmError> {
    let token = if use_oidc {
        oidc::exchange_oidc_token(registry_url, None, "read")
            .await
            .map(|oidc_token| ResolvedSetupBearer::oidc(oidc_token.token))
            .map_err(|error| {
                LpmError::Script(format!(
                    "OIDC token exchange failed; no fallback was used: {error}"
                ))
            })?
    } else {
        resolve_lpm_bearer(registry_url, json_output).await?
    };

    let storage_status = setup_storage_status(&token);
    if token.token.is_empty()
        || !token.token.bytes().all(|byte| {
            byte.is_ascii_alphanumeric()
                || matches!(byte, b'-' | b'.' | b'_' | b'~' | b'+' | b'/' | b'=')
        })
    {
        return Err(LpmError::Script(
            "the resolved bearer is malformed and cannot be written safely to .npmrc".into(),
        ));
    }

    let registry_host = registry_url
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .trim_end_matches('/');

    let registry_line = format!(
        "@lpm.dev:registry={}/api/registry/",
        registry_url.trim_end_matches('/')
    );

    let clean_generated = format!(
        "{GENERATED_HEADER}\n//{}/:_authToken={}\n{}\n{GENERATED_END}",
        registry_host, token.token, registry_line
    );
    let npmrc_path = project_dir.join(".npmrc");
    let existing =
        match lpm_common::read_text_file_capped(&npmrc_path, lpm_common::NPMRC_FILE_SIZE_CAP_BYTES)
        {
            Ok(content) => content,
            Err(lpm_common::BoundedReadError::NotFound { .. }) => String::new(),
            Err(error) => return Err(error.into()),
        };
    if let Some(local_registry) = super::npmrc::local_setup_registry_url(&existing) {
        let registry_base = registry_url.trim_end_matches('/');
        let expected_registry = if registry_base.ends_with("/api/registry") {
            registry_base.to_string()
        } else {
            format!("{registry_base}/api/registry")
        };
        if local_registry != expected_registry {
            return Err(LpmError::Script(format!(
                "the setup-local token belongs to {local_registry}; rerun with its registry before replacing the generated block"
            )));
        }
    }
    if let Some(predecessor_bearer) = super::npmrc::setup_ci_predecessor_bearer(&existing)? {
        if predecessor_bearer == token.token {
            return Err(LpmError::Script(
                "setup ci cannot replace a setup-local token with the same bearer because retiring it would make the generated credential unusable. Supply a different bearer through LPM_TOKEN, a stored session, or --oidc"
                    .into(),
            ));
        }
        if let Err(error) =
            super::npmrc::self_revoke_project_token(client, registry_url, &predecessor_bearer).await
        {
            return Err(LpmError::Registry(format!(
                "{error}. The protected .npmrc still contains the displaced setup token; rerun `lpm setup ci npmrc` with the same registry to retry safely"
            )));
        }
    }
    let npmrc_content = replace_generated_block(&existing, &clean_generated, registry_host);
    lpm_common::write_file_atomic_with_options(
        &npmrc_path,
        &npmrc_content,
        lpm_common::AtomicWriteOptions::new().unix_mode(0o600),
    )?;

    if json_output {
        let safe_content = format!(
            "{GENERATED_HEADER}\n//{registry_host}/:_authToken=<redacted>\n{registry_line}\n{GENERATED_END}\n"
        );
        let json = serde_json::json!({
            "success": true,
            "path": npmrc_path.display().to_string(),
            "content": safe_content,
            "uses_env_var": token.uses_env_var,
            "oidc": use_oidc,
            "proxy": false,
            "storage_backend": storage_status.backend_json_value(),
            "storage_degraded": storage_status.degraded,
            "note": "JSON redacts the bearer; the protected on-disk .npmrc contains the runtime-resolved literal token for npm-compatible clients.",
        });
        let rendered = serde_json::to_string_pretty(&json)
            .map_err(|error| LpmError::Script(format!("failed to encode JSON output: {error}")))?;
        println!("{rendered}");
    } else {
        install_ui::done("Generated .npmrc");
        hint_line(&npmrc_path.display().to_string());

        if use_oidc {
            install_ui::phase("Using OIDC-exchanged token.");
        }
        install_ui::phase(
            "The protected file contains a literal bearer for npm-compatible clients; LPM CLI can consume LPM_TOKEN directly.",
        );
    }

    Ok(())
}

fn replace_generated_block(existing: &str, generated: &str, registry_host: &str) -> String {
    let auth_prefix = format!("//{registry_host}/:_authToken=");
    let lines: Vec<_> = existing.lines().collect();
    let mut kept = Vec::with_capacity(lines.len());
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index];
        if is_generated_header(line) {
            let next_boundary = lines[index + 1..]
                .iter()
                .position(|candidate| *candidate == GENERATED_END || is_generated_header(candidate))
                .map(|offset| index + 1 + offset);
            index = match next_boundary {
                Some(end) if lines[end] == GENERATED_END => end + 1,
                _ => {
                    let mut end = index + 1;
                    while lines.get(end).is_some_and(|line| {
                        line.starts_with("# LPM project token id: ")
                            || line.starts_with("# LPM pending project token id: ")
                            || line.starts_with("# LPM previous project token id: ")
                            || line.starts_with("# LPM previous project token hash: ")
                            || line.starts_with("# LPM previous project token bearer: ")
                            || line.starts_with("# LPM pending project token retirement id: ")
                            || line.starts_with("# LPM pending project token retirement hash: ")
                            || line.starts_with("@lpm.dev:registry=")
                            || line.contains("/:_authToken=")
                    }) {
                        end += 1;
                    }
                    end
                }
            };
            continue;
        }
        if line.starts_with(&auth_prefix)
            || line.starts_with("@lpm.dev:registry=") && line.contains("/api/registry")
        {
            index += 1;
            continue;
        }
        kept.push(line);
        index += 1;
    }
    let prefix = kept.join("\n").trim().to_string();
    if prefix.is_empty() {
        format!("{generated}\n")
    } else {
        format!("{prefix}\n\n{generated}\n")
    }
}

fn is_generated_header(line: &str) -> bool {
    line == GENERATED_HEADER || line == LOCAL_GENERATED_HEADER
}

pub fn run_ci_platform(platform: &str, project_dir: &Path, env_mode: &str) -> Result<(), LpmError> {
    match platform {
        "github-actions" | "github" | "gha" => {
            setup_github_actions(project_dir, env_mode);
            Ok(())
        }
        "gitlab" | "gitlab-ci" => {
            setup_gitlab_ci(env_mode);
            Ok(())
        }
        _ => Err(LpmError::Script(format!(
            "unknown CI setup target: '{platform}'. Available: npmrc, github-actions, gitlab"
        ))),
    }
}

fn setup_github_actions(project_dir: &Path, env_mode: &str) {
    let vault_id = lpm_vault::vault_id::read_vault_id(project_dir)
        .unwrap_or_else(|| "<your-vault-id>".to_string());
    let env_mode = install_ui::field(env_mode);
    let vault_id = install_ui::field(&vault_id);

    println!();
    println!("  {} GitHub Actions OIDC Setup", "▸".bold());
    println!();
    println!(
        "  {} Add this to your workflow (.github/workflows/deploy.yml):",
        "1.".bold()
    );
    println!();
    println!(
        "  {}",
        "jobs:
    deploy:
      permissions:
        id-token: write
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: Install LPM
          run: npm install -g @lpm-registry/cli
        - name: Load secrets from env
          run: lpm env pull --oidc --env={ENV} --output=.env
          env:
            LPM_VAULT_ID: {VAULT_ID}
        - name: Deploy
          run: lpm run deploy"
            .replace("{ENV}", env_mode.as_ref())
            .replace("{VAULT_ID}", vault_id.as_ref())
            .dimmed()
    );
    println!();
    println!("  {} Authorize this repo:", "2.".bold());
    println!();
    println!(
        "  {}",
        format!(
            "lpm env oidc allow --provider=github --repo=<owner/repo> \
             --workflow=.github/workflows/deploy.yml --branch=main --env={env_mode}"
        )
        .bold()
    );
    println!();
}

fn setup_gitlab_ci(env_mode: &str) {
    let env_mode = install_ui::field(env_mode);

    println!();
    println!("  {} GitLab CI OIDC Setup", "▸".bold());
    println!();
    println!("  {} Add this to .gitlab-ci.yml:", "1.".bold());
    println!();
    println!(
        "  {}",
        "deploy:
  id_tokens:
    LPM_OIDC_TOKEN:
      aud: https://lpm.dev
  script:
    - npm install -g @lpm-registry/cli
    - lpm env pull --oidc --env={ENV} --output=.env
    - lpm run deploy"
            .replace("{ENV}", env_mode.as_ref())
            .dimmed()
    );
    println!();
    println!("  {} Authorize this project:", "2.".bold());
    println!();
    println!(
        "  {}",
        format!(
            "lpm env oidc allow --provider=gitlab --project-id=<numeric-project-id> --branch=main --env={env_mode}"
        )
        .bold()
    );
    println!();
}
