#!/usr/bin/env python3
"""Export the pinned portable validator after its wasm32 release build."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile

def decoder_module(binary):
    encoded = base64.b64encode(binary).decode('ascii')
    return ('// biome-ignore-all lint: generated portable Rust validator\n'
            'export function wasmBytes() {\n'
            '\tconst decoded = atob("' + encoded + '")\n'
            '\tconst bytes = new Uint8Array(decoded.length)\n'
            '\tfor (let index = 0; index < decoded.length; index++) {\n'
            '\t\tbytes[index] = decoded.charCodeAt(index)\n'
            '\t}\n'
            '\treturn bytes\n'
            '}\n')


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--target-dir', type=Path, required=True)
    parser.add_argument('--wasm-bindgen', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    version = subprocess.check_output([str(args.wasm_bindgen), '--version'], text=True).strip()
    if version != 'wasm-bindgen 0.2.122':
        raise SystemExit('Use wasm-bindgen-cli 0.2.122 to match Cargo.lock')
    wasm = args.target_dir / 'wasm32-unknown-unknown/release/lpm_env_wasm.wasm'
    args.output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='lpm-env-validator-') as temporary:
        subprocess.run([str(args.wasm_bindgen), str(wasm), '--target', 'web', '--out-name', 'validator', '--out-dir', temporary], check=True)
        generated = Path(temporary)
        binary = (generated / 'validator_bg.wasm').read_bytes()
        glue = (generated / 'validator.js').read_text().replace('/* @ts-self-types="./validator.d.ts" */', '')
        glue = glue[:glue.index('async function __wbg_init(')] + 'export { initSync };\n'
        (args.output / 'validator.js').write_text('// biome-ignore-all lint: generated by pinned wasm-bindgen\n' + glue)
        (args.output / 'wasm.js').write_text(decoder_module(binary))
        inputs = sorted((root / 'crates/lpm-env/src').rglob('*.rs')) + [root / 'crates/lpm-env/Cargo.toml', root / 'crates/lpm-env-wasm/src/lib.rs', root / 'crates/lpm-env-wasm/Cargo.toml', root / 'Cargo.lock']
        sources = {str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest() for path in inputs}
        provenance = {'toolchain': '1.94.0', 'wasmBindgen': '0.2.122', 'wasmSha256': hashlib.sha256(binary).hexdigest(), 'wasmBytes': len(binary), 'sources': sources}
        (args.output / 'provenance.json').write_text(json.dumps(provenance, indent=2) + '\n')
        print(f'Exported {len(binary)} bytes to {args.output}')


if __name__ == '__main__':
    main()
