#!/usr/bin/env python3
"""Export the pinned portable validator after its wasm32 release build."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile

def decoder_module(binary):
    encoded = base64.b64encode(binary).decode('ascii')
    return ('// biome-ignore-all lint: generated portable Rust validator\n'
            'export function wasmBytes() {\n'
            '\tconst decoded = atob("' + encoded + '")\n'
            '\tconst bytes = new Uint8Array(decoded.length)\n'
            '\tfor (let index = 0; index < decoded.length; index++) {\n'
            '\t\tbytes[index] = decoded.charCodeAt(index)\n'
            '\t}\n'
            '\treturn bytes\n'
            '}\n')


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--target-dir', type=Path, required=True)
    parser.add_argument('--wasm-bindgen', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    inputs = sorted((root / 'crates/lpm-env/src').rglob('*.rs')) + sorted((root / 'crates/lpm-env-wasm/src').rglob('*.rs')) + [root / name for name in (
        'Cargo.toml', 'Cargo.lock', 'rust-toolchain.toml', '.cargo/config.toml',
        'crates/lpm-env/Cargo.toml', 'crates/lpm-env-wasm/Cargo.toml',
        'scripts/export-env-validator.py',
    )]
    names = [str(path.relative_to(root)) for path in inputs]
    def clean_revision():
        dirty = subprocess.check_output(['git', '-C', str(root), 'status', '--porcelain', '--untracked-files=all', '--', *names], text=True)
        if dirty:
            raise SystemExit('Export requires clean committed build inputs')
        return subprocess.check_output(['git', '-C', str(root), 'rev-parse', 'HEAD'], text=True).strip()
    revision = clean_revision()
    sources = {name: hashlib.sha256(path.read_bytes()).hexdigest() for name, path in zip(names, inputs)}
    version = subprocess.check_output([str(args.wasm_bindgen), '--version'], text=True).strip()
    if version != 'wasm-bindgen 0.2.122':
        raise SystemExit('Use wasm-bindgen-cli 0.2.122 to match Cargo.lock')
    wasm = args.target_dir / 'wasm32-unknown-unknown/release/lpm_env_wasm.wasm'
    with tempfile.TemporaryDirectory(prefix='lpm-env-validator-') as temporary:
        subprocess.run([str(args.wasm_bindgen), str(wasm), '--target', 'web', '--out-name', 'validator', '--out-dir', temporary], check=True)
        generated = Path(temporary)
        binary = (generated / 'validator_bg.wasm').read_bytes()
        glue = (generated / 'validator.js').read_text().replace('/* @ts-self-types="./validator.d.ts" */', '')
        glue = glue[:glue.index('async function __wbg_init(')] + 'export { initSync };\n'
        artifacts = {'validator.js': ('// biome-ignore-all lint: generated by pinned wasm-bindgen\n' + glue).encode(), 'wasm.js': decoder_module(binary).encode()}
        if clean_revision() != revision or any(hashlib.sha256(path.read_bytes()).hexdigest() != sources[name] for name, path in zip(names, inputs)):
            raise SystemExit('Export requires stable clean committed build inputs')
        provenance = {'repository': 'https://github.com/lpm-dev/rust-client.git', 'revision': revision, 'toolchain': '1.94.0', 'wasmBindgen': '0.2.122', 'wasmSha256': hashlib.sha256(binary).hexdigest(), 'wasmBytes': len(binary), 'sources': sources, 'artifacts': {name: hashlib.sha256(data).hexdigest() for name, data in artifacts.items()}}
        args.output.mkdir(parents=True, exist_ok=True)
        for name, data in artifacts.items():
            (args.output / name).write_bytes(data)
        (args.output / 'provenance.json').write_text(json.dumps(provenance, indent=2) + '\n')
        print(f'Exported {len(binary)} bytes to {args.output}')


if __name__ == '__main__':
    main()
