//! CI template generation for post-migration projects.
//!
//! Detects the CI platform from existing config files and generates
//! an appropriate template that uses `lpm install` instead of npm/yarn/pnpm.

use std::path::Path;

/// Supported CI platforms.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CiPlatform {
    GitHubActions,
    GitLabCi,
    CircleCi,
    Bitbucket,
}

impl std::fmt::Display for CiPlatform {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CiPlatform::GitHubActions => write!(f, "GitHub Actions"),
            CiPlatform::GitLabCi => write!(f, "GitLab CI"),
            CiPlatform::CircleCi => write!(f, "CircleCI"),
            CiPlatform::Bitbucket => write!(f, "Bitbucket Pipelines"),
        }
    }
}

/// Detect the CI platform from existing configuration files.
pub fn detect_ci_platform(project_dir: &Path) -> Option<CiPlatform> {
    // Check in order of popularity
    if project_dir.join(".github/workflows").is_dir() {
        return Some(CiPlatform::GitHubActions);
    }
    if project_dir.join(".gitlab-ci.yml").exists() {
        return Some(CiPlatform::GitLabCi);
    }
    if project_dir.join(".circleci/config.yml").exists() {
        return Some(CiPlatform::CircleCi);
    }
    if project_dir.join("bitbucket-pipelines.yml").exists() {
        return Some(CiPlatform::Bitbucket);
    }

    None
}

/// Get the output file path for the CI template.
///
/// Uses a `.lpm` suffix to avoid overwriting existing CI configs.
pub fn template_output_path(project_dir: &Path, platform: CiPlatform) -> std::path::PathBuf {
    match platform {
        CiPlatform::GitHubActions => project_dir.join(".github/workflows/ci.lpm.yml"),
        CiPlatform::GitLabCi => project_dir.join(".gitlab-ci.lpm.yml"),
        CiPlatform::CircleCi => project_dir.join(".circleci/config.lpm.yml"),
        CiPlatform::Bitbucket => project_dir.join("bitbucket-pipelines.lpm.yml"),
    }
}

/// Generate a CI template for the detected platform.
pub fn generate_template(platform: CiPlatform) -> String {
    match platform {
        CiPlatform::GitHubActions => generate_github_actions(),
        CiPlatform::GitLabCi => generate_gitlab_ci(),
        CiPlatform::CircleCi => generate_circleci(),
        CiPlatform::Bitbucket => generate_bitbucket(),
    }
}

fn generate_github_actions() -> String {
    r#"# .github/workflows/ci.yml
# Generated by `lpm migrate` — adjust to your needs.
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install LPM
        run: npm install -g @lpm-registry/cli

      - name: Install dependencies
        run: lpm install
        env:
          LPM_TOKEN: ${{ secrets.LPM_TOKEN }}

      - name: Build
        run: lpm run build

      - name: Test
        run: lpm run test
"#
    .to_string()
}

fn generate_gitlab_ci() -> String {
    r#"# .gitlab-ci.yml
# Generated by `lpm migrate` — adjust to your needs.
# Add LPM_TOKEN to your GitLab CI/CD variables:
#   Settings → CI/CD → Variables → Add variable (masked, protected)
image: node:22

stages:
  - install
  - build
  - test

install:
  stage: install
  script:
    - npm install -g @lpm-registry/cli
    - lpm install
  variables:
    LPM_TOKEN: $LPM_TOKEN
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - lpm run build
  dependencies:
    - install

test:
  stage: test
  script:
    - lpm run test
  dependencies:
    - install
"#
    .to_string()
}

fn generate_circleci() -> String {
    r#"# .circleci/config.yml
# Generated by `lpm migrate` — adjust to your needs.
# Add LPM_TOKEN to your CircleCI project environment variables:
#   Project Settings → Environment Variables → Add Variable
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.0
    environment:
      LPM_TOKEN: ${LPM_TOKEN}
    steps:
      - checkout
      - run:
          name: Install LPM
          command: npm install -g @lpm-registry/cli
      - run:
          name: Install dependencies
          command: lpm install
      - run:
          name: Build
          command: lpm run build
      - run:
          name: Test
          command: lpm run test

workflows:
  main:
    jobs:
      - build-and-test
"#
    .to_string()
}

fn generate_bitbucket() -> String {
    r#"# bitbucket-pipelines.yml
# Generated by `lpm migrate` — adjust to your needs.
# Add LPM_TOKEN to your Bitbucket pipeline variables:
#   Repository Settings → Pipeline → Repository variables
image: node:22

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install -g @lpm-registry/cli
          - lpm install
          - lpm run build
          - lpm run test
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn detect_github_actions() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join(".github/workflows")).unwrap();

        let platform = detect_ci_platform(dir.path());
        assert_eq!(platform, Some(CiPlatform::GitHubActions));
    }

    #[test]
    fn detect_gitlab_ci() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(".gitlab-ci.yml"), "stages:\n  - build").unwrap();

        let platform = detect_ci_platform(dir.path());
        assert_eq!(platform, Some(CiPlatform::GitLabCi));
    }

    #[test]
    fn detect_circleci() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join(".circleci")).unwrap();
        fs::write(dir.path().join(".circleci/config.yml"), "version: 2.1").unwrap();

        let platform = detect_ci_platform(dir.path());
        assert_eq!(platform, Some(CiPlatform::CircleCi));
    }

    #[test]
    fn detect_bitbucket() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("bitbucket-pipelines.yml"), "pipelines:").unwrap();

        let platform = detect_ci_platform(dir.path());
        assert_eq!(platform, Some(CiPlatform::Bitbucket));
    }

    #[test]
    fn detect_none() {
        let dir = tempfile::tempdir().unwrap();
        let platform = detect_ci_platform(dir.path());
        assert_eq!(platform, None);
    }

    #[test]
    fn template_contains_lpm_install() {
        for platform in [
            CiPlatform::GitHubActions,
            CiPlatform::GitLabCi,
            CiPlatform::CircleCi,
            CiPlatform::Bitbucket,
        ] {
            let template = generate_template(platform);
            assert!(
                template.contains("lpm install"),
                "{} template should contain 'lpm install'",
                platform
            );
            assert!(
                template.contains("lpm run build"),
                "{} template should contain 'lpm run build'",
                platform
            );
            assert!(
                template.contains("lpm run test"),
                "{} template should contain 'lpm run test'",
                platform
            );
        }
    }

    #[test]
    fn all_platforms_have_lpm_token() {
        for platform in [
            CiPlatform::GitHubActions,
            CiPlatform::GitLabCi,
            CiPlatform::CircleCi,
            CiPlatform::Bitbucket,
        ] {
            let template = generate_template(platform);
            assert!(
                template.contains("LPM_TOKEN"),
                "{} template should contain LPM_TOKEN",
                platform
            );
        }
    }

    #[test]
    fn priority_github_over_gitlab() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join(".github/workflows")).unwrap();
        fs::write(dir.path().join(".gitlab-ci.yml"), "stages:").unwrap();

        let platform = detect_ci_platform(dir.path());
        assert_eq!(platform, Some(CiPlatform::GitHubActions));
    }

    #[test]
    fn template_output_path_github() {
        let dir = tempfile::tempdir().unwrap();
        let path = template_output_path(dir.path(), CiPlatform::GitHubActions);
        assert_eq!(path, dir.path().join(".github/workflows/ci.lpm.yml"));
    }

    #[test]
    fn template_output_path_gitlab() {
        let dir = tempfile::tempdir().unwrap();
        let path = template_output_path(dir.path(), CiPlatform::GitLabCi);
        assert_eq!(path, dir.path().join(".gitlab-ci.lpm.yml"));
    }

    #[test]
    fn template_output_path_circleci() {
        let dir = tempfile::tempdir().unwrap();
        let path = template_output_path(dir.path(), CiPlatform::CircleCi);
        assert_eq!(path, dir.path().join(".circleci/config.lpm.yml"));
    }

    #[test]
    fn template_output_path_bitbucket() {
        let dir = tempfile::tempdir().unwrap();
        let path = template_output_path(dir.path(), CiPlatform::Bitbucket);
        assert_eq!(path, dir.path().join("bitbucket-pipelines.lpm.yml"));
    }
}
