// Generated from the coverage matrix. See the audit doc at

// Update the command matrix first, then re-generate this file when the audited
// command-surface baseline changes.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum JsonContractStatus {
    Covered,
    NotApplicable,
    Missing,
}

impl JsonContractStatus {
    pub const fn has_contract(self) -> bool {
        matches!(self, Self::Covered)
    }

    pub const fn is_accounted_for(self) -> bool {
        !matches!(self, Self::Missing)
    }
}

#[derive(Debug)]
pub struct SurfaceBaseline {
    pub id: u16,
    pub name: &'static str,
    pub unit: bool,
    pub integration: bool,
    pub workflow: bool,
    pub cli_binary: bool,
    pub json_contract: JsonContractStatus,
    pub references: &'static [&'static str],
}

impl SurfaceBaseline {
    pub const fn has_any_coverage(&self) -> bool {
        self.unit
            || self.integration
            || self.workflow
            || self.cli_binary
            || self.json_contract.has_contract()
    }
}

pub const EXPECTED_SURFACE_COUNT: usize = 152;

pub const EXPECTED_COMMAND_VARIANTS: &[&str] = &[
    "Info",
    "Search",
    "Quality",
    "Whoami",
    "Health",
    "Download",
    "Resolve",
    "Install",
    "Uninstall",
    "Add",
    "Publish",
    "Stage",
    "Login",
    "Logout",
    "Setup",
    "TokenRotate",
    "Outdated",
    "Upgrade",
    "Init",
    "Config",
    "Cache",
    "Store",
    "Catalog",
    "Global",
    "Trust",
    "Pool",
    "Skills",
    "Remove",
    "Audit",
    "Query",
    "Rebuild",
    "Doctor",
    "SwiftRegistry",
    "Mcp",
    "Use",
    "Env",
    "Run",
    "Exec",
    "Dlx",
    "Deploy",
    "ApproveScripts",
    "Patch",
    "PatchCommit",
    "PatchRemove",
    "Sbom",
    "Filter",
    "Plugin",
    "Lint",
    "Fmt",
    "Check",
    "Bundle",
    "Pack",
    "Test",
    "Bench",
    "Ci",
    "Dev",
    "Cert",
    "Graph",
    "Ports",
    "Hosts",
    "Proxy",
    "Tunnel",
    "Migrate",
    "Vault",
    "Security",
    "SelfUpdate",
    "InternalHostsFile",
    "InternalUpdateCheck",
    "Completions",
    "Schema",
    "External",
];

pub const SURFACES: &[SurfaceBaseline] = &[
    SurfaceBaseline {
        id: 1,
        name: "`lpm info <pkg>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/json_output.rs"],
    },
    SurfaceBaseline {
        id: 2,
        name: "`lpm search <query>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/search.rs"],
    },
    SurfaceBaseline {
        id: 3,
        name: "`lpm quality <pkg>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/quality.rs"],
    },
    SurfaceBaseline {
        id: 4,
        name: "`lpm whoami`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/auth_lifecycle.rs",
            "tests/workflows/tests/json_output.rs",
        ],
    },
    SurfaceBaseline {
        id: 5,
        name: "`lpm health`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/json_output.rs"],
    },
    SurfaceBaseline {
        id: 6,
        name: "`lpm download <pkg>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/download.rs"],
    },
    SurfaceBaseline {
        id: 7,
        name: "`lpm resolve <pkgs>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/resolve.rs"],
    },
    SurfaceBaseline {
        id: 8,
        name: "`lpm outdated`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/outdated.rs"],
    },
    SurfaceBaseline {
        id: 9,
        name: "`lpm doctor`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/doctor/mod.rs",
            "tests/workflows/tests/doctor_list.rs",
            "tests/workflows/tests/json_output.rs",
            "crates/lpm-cli/tests/global_install_state_mutation.rs",
        ],
    },
    SurfaceBaseline {
        id: 10,
        name: "`lpm doctor --fix`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/doctor_fix.rs"],
    },
    SurfaceBaseline {
        id: 11,
        name: "`lpm init`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/init.rs"],
    },
    SurfaceBaseline {
        id: 12,
        name: "`lpm install` (bare, lockfile fast-path)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/install/mod.rs",
            "tests/workflows/tests/install.rs",
            "tests/workflows/tests/install_overrides.rs",
            "tests/workflows/tests/install_patches.rs",
            "tests/workflows/tests/install_real_registry.rs",
        ],
    },
    SurfaceBaseline {
        id: 13,
        name: "`lpm install <pkg>` (add-and-install)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/install.rs"],
    },
    SurfaceBaseline {
        id: 14,
        name: "`lpm install --offline`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/install.rs",
            "tests/workflows/tests/install_offline_capability_roundtrip.rs",
        ],
    },
    SurfaceBaseline {
        id: 15,
        name: "`lpm install --filter / -w` (workspace)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/install.rs"],
    },
    SurfaceBaseline {
        id: 16,
        name: "`lpm install -g` (global)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/install_global.rs",
            "crates/lpm-cli/tests/global_install_state_mutation.rs",
            "tests/workflows/tests/global.rs",
            "tests/workflows/tests/install_global_security.rs",
        ],
    },
    SurfaceBaseline {
        id: 17,
        name: "`lpm install --policy / --yolo`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/install_policy.rs"],
    },
    SurfaceBaseline {
        id: 18,
        name: "`lpm install --strict-integrity / provenance / cooldown`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/install_provenance.rs",
            "tests/workflows/tests/install.rs",
        ],
    },
    SurfaceBaseline {
        id: 19,
        name: "`lpm uninstall <pkg>` (project)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/uninstall.rs",
            "tests/workflows/tests/uninstall.rs",
        ],
    },
    SurfaceBaseline {
        id: 20,
        name: "`lpm uninstall -g` (global)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/uninstall_global.rs",
            "crates/lpm-cli/tests/global_install_state_mutation.rs",
            "tests/workflows/tests/global.rs",
        ],
    },
    SurfaceBaseline {
        id: 21,
        name: "`lpm uninstall --filter / -w`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/uninstall.rs"],
    },
    SurfaceBaseline {
        id: 22,
        name: "`lpm add <pkg>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/add/mod.rs",
            "tests/workflows/tests/add.rs",
        ],
    },
    SurfaceBaseline {
        id: 23,
        name: "`lpm remove <pkg>` (alias `rm`, source pkg)",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/remove.rs"],
    },
    SurfaceBaseline {
        id: 24,
        name: "`lpm upgrade` (bare)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/upgrade.rs",
            "tests/workflows/tests/upgrade.rs",
        ],
    },
    SurfaceBaseline {
        id: 25,
        name: "`lpm upgrade --major`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/upgrade.rs"],
    },
    SurfaceBaseline {
        id: 26,
        name: "`lpm upgrade --interactive`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/upgrade.rs"],
    },
    SurfaceBaseline {
        id: 27,
        name: "`lpm publish` (LPM, default)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/publish.rs",
            "tests/workflows/tests/publish.rs",
            "crates/lpm-cli/tests/oidc_publish_auto_exchange_contract.rs",
        ],
    },
    SurfaceBaseline {
        id: 28,
        name: "`lpm publish --npm`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/publish_npm.rs",
            "crates/lpm-cli/tests/oidc_publish_auto_exchange_contract.rs",
            "tests/workflows/tests/publish.rs",
        ],
    },
    SurfaceBaseline {
        id: 29,
        name: "`lpm publish --github`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/publish.rs"],
    },
    SurfaceBaseline {
        id: 30,
        name: "`lpm publish --gitlab`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/publish.rs"],
    },
    SurfaceBaseline {
        id: 31,
        name: "`lpm publish --publish-registry <URL>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/publish.rs"],
    },
    SurfaceBaseline {
        id: 32,
        name: "`lpm publish --dry-run`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/publish.rs",
            "crates/lpm-cli/tests/oidc_publish_auto_exchange_contract.rs",
        ],
    },
    SurfaceBaseline {
        id: 33,
        name: "`lpm publish --check`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/publish.rs",
            "crates/lpm-cli/tests/oidc_publish_auto_exchange_contract.rs",
        ],
    },
    SurfaceBaseline {
        id: 34,
        name: "`lpm login` (LPM default)",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/auth_lifecycle.rs",
            "tests/workflows/tests/json_output.rs",
        ],
    },
    SurfaceBaseline {
        id: 35,
        name: "`lpm login --npm`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/auth_lifecycle.rs",
            "tests/workflows/tests/npmrc.rs",
        ],
    },
    SurfaceBaseline {
        id: 36,
        name: "`lpm login --github / --gitlab`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/auth_lifecycle.rs",
            "crates/lpm-cli/tests/oidc_setup_snippet_contract.rs",
        ],
    },
    SurfaceBaseline {
        id: 37,
        name: "`lpm login --login-registry <URL>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/auth_lifecycle.rs"],
    },
    SurfaceBaseline {
        id: 38,
        name: "`lpm logout`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/auth_lifecycle.rs"],
    },
    SurfaceBaseline {
        id: 39,
        name: "`lpm logout --revoke / --all`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/auth_lifecycle.rs"],
    },
    SurfaceBaseline {
        id: 40,
        name: "`lpm token-rotate`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/token_rotate.rs"],
    },
    SurfaceBaseline {
        id: 41,
        name: "`lpm setup ci` (.npmrc CI gen)",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/tests/oidc_setup_snippet_contract.rs",
            "tests/workflows/tests/setup_ci.rs",
        ],
    },
    SurfaceBaseline {
        id: 42,
        name: "`lpm setup local`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/setup_local.rs"],
    },
    SurfaceBaseline {
        id: 43,
        name: "`lpm config get`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/config.rs"],
    },
    SurfaceBaseline {
        id: 44,
        name: "`lpm config set`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/config.rs"],
    },
    SurfaceBaseline {
        id: 45,
        name: "`lpm config delete`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/config.rs"],
    },
    SurfaceBaseline {
        id: 46,
        name: "`lpm config list`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/config.rs"],
    },
    SurfaceBaseline {
        id: 47,
        name: "`lpm cache clean [subcat]`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/cache.rs",
            "tests/workflows/tests/cache.rs",
        ],
    },
    SurfaceBaseline {
        id: 48,
        name: "`lpm cache path [subcat]`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/cache.rs"],
    },
    SurfaceBaseline {
        id: 49,
        name: "`lpm store verify`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/store.rs",
            "tests/workflows/tests/store.rs",
        ],
    },
    SurfaceBaseline {
        id: 50,
        name: "`lpm store path`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/store.rs"],
    },
    SurfaceBaseline {
        id: 51,
        name: "`lpm cache prune`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/cache_prune.rs",
            "tests/workflows/tests/cache_prune.rs",
        ],
    },
    SurfaceBaseline {
        id: 52,
        name: "`lpm store clean`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/store.rs"],
    },
    SurfaceBaseline {
        id: 53,
        name: "`lpm global list`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/global.rs",
            "crates/lpm-cli/tests/global_install_state_mutation.rs",
            "tests/workflows/tests/global.rs",
        ],
    },
    SurfaceBaseline {
        id: 54,
        name: "`lpm global list --outdated`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/tests/global_install_state_mutation.rs",
            "tests/workflows/tests/global.rs",
        ],
    },
    SurfaceBaseline {
        id: 55,
        name: "`lpm global bin`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/global.rs"],
    },
    SurfaceBaseline {
        id: 56,
        name: "`lpm global path <pkg>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/global.rs"],
    },
    SurfaceBaseline {
        id: 57,
        name: "`lpm global remove`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/tests/global_install_state_mutation.rs",
            "tests/workflows/tests/global.rs",
        ],
    },
    SurfaceBaseline {
        id: 58,
        name: "`lpm global update`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/update_global.rs",
            "crates/lpm-cli/tests/global_install_state_mutation.rs",
            "tests/workflows/tests/global.rs",
        ],
    },
    SurfaceBaseline {
        id: 59,
        name: "`lpm trust diff`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/trust.rs",
            "tests/workflows/tests/trust.rs",
        ],
    },
    SurfaceBaseline {
        id: 60,
        name: "`lpm trust prune`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/trust.rs"],
    },
    SurfaceBaseline {
        id: 61,
        name: "`lpm pool`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/pool.rs"],
    },
    SurfaceBaseline {
        id: 62,
        name: "`lpm audit`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/audit/mod.rs",
            "tests/workflows/tests/audit.rs",
        ],
    },
    SurfaceBaseline {
        id: 63,
        name: "`lpm audit --fail-on=<policy>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/audit.rs"],
    },
    SurfaceBaseline {
        id: 64,
        name: "`lpm audit --secrets`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/audit.rs"],
    },
    SurfaceBaseline {
        id: 65,
        name: "`lpm query <selector>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/query.rs",
            "tests/workflows/tests/query.rs",
        ],
    },
    SurfaceBaseline {
        id: 66,
        name: "`lpm query --count / --assert-none / --format mermaid`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/query.rs"],
    },
    SurfaceBaseline {
        id: 67,
        name: "`lpm rebuild` (bare, trusted-only)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/rebuild/mod.rs",
            "tests/workflows/tests/approve_scripts.rs",
            "tests/workflows/tests/cross_command_flows.rs",
            "tests/workflows/tests/rebuild.rs",
            "tests/workflows/tests/triage_install_lifecycle.rs",
        ],
    },
    SurfaceBaseline {
        id: 68,
        name: "`lpm rebuild --all`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/rebuild.rs"],
    },
    SurfaceBaseline {
        id: 69,
        name: "`lpm rebuild --policy=allow / --yolo`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/rebuild.rs"],
    },
    SurfaceBaseline {
        id: 70,
        name: "`lpm rebuild --policy=triage / --triage`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/rebuild.rs"],
    },
    SurfaceBaseline {
        id: 71,
        name: "`lpm approve-scripts` (interactive)",
        unit: true,
        integration: false,
        workflow: false,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/approve_scripts/mod.rs",
            "crates/lpm-cli/tests/approve_scripts_interactive_tty.rs",
        ],
    },
    SurfaceBaseline {
        id: 72,
        name: "`lpm approve-scripts --list`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/approve_scripts.rs"],
    },
    SurfaceBaseline {
        id: 73,
        name: "`lpm approve-scripts --yes`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/approve_scripts.rs"],
    },
    SurfaceBaseline {
        id: 74,
        name: "`lpm approve-scripts <pkg>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/approve_scripts.rs"],
    },
    SurfaceBaseline {
        id: 75,
        name: "`lpm approve-scripts --global`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/approve_scripts.rs",
            "tests/workflows/tests/install_global_security.rs",
        ],
    },
    SurfaceBaseline {
        id: 76,
        name: "`lpm approve-scripts --dry-run`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/approve_scripts.rs"],
    },
    SurfaceBaseline {
        id: 77,
        name: "`lpm patch <key>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/patch.rs",
            "tests/workflows/tests/patch.rs",
        ],
    },
    SurfaceBaseline {
        id: 78,
        name: "`lpm patch-commit <dir>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/patch.rs"],
    },
    SurfaceBaseline {
        id: 79,
        name: "`lpm filter <expr>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/filter.rs",
            "tests/workflows/tests/filter.rs",
        ],
    },
    SurfaceBaseline {
        id: 80,
        name: "`lpm deploy <out> --filter`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/deploy.rs",
            "tests/workflows/tests/deploy.rs",
        ],
    },
    SurfaceBaseline {
        id: 81,
        name: "`lpm plugin list / update`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/plugin.rs"],
    },
    SurfaceBaseline {
        id: 82,
        name: "`lpm skills list/install/validate/clean`",
        unit: true,
        integration: true,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/skills.rs",
            "tests/integration/tests/output_parity.rs",
            "tests/workflows/tests/skills.rs",
        ],
    },
    SurfaceBaseline {
        id: 83,
        name: "`lpm run <script>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/run.rs",
            "tests/workflows/tests/run.rs",
            "tests/workflows/tests/json_output.rs",
        ],
    },
    SurfaceBaseline {
        id: 84,
        name: "`lpm run --filter / --all / --affected`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/run.rs"],
    },
    SurfaceBaseline {
        id: 85,
        name: "`lpm exec <file>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/exec.rs"],
    },
    SurfaceBaseline {
        id: 86,
        name: "`lpm dlx <pkg>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/dlx.rs"],
    },
    SurfaceBaseline {
        id: 87,
        name: "`lpm lint`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/tools.rs",
            "tests/workflows/tests/tools.rs",
        ],
    },
    SurfaceBaseline {
        id: 88,
        name: "`lpm fmt` (write)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/tools.rs"],
    },
    SurfaceBaseline {
        id: 89,
        name: "`lpm fmt --check`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/tools.rs"],
    },
    SurfaceBaseline {
        id: 90,
        name: "`lpm check`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/check_typescript.rs",
            "tests/workflows/tests/tools.rs",
        ],
    },
    SurfaceBaseline {
        id: 91,
        name: "`lpm test`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/tools.rs"],
    },
    SurfaceBaseline {
        id: 92,
        name: "`lpm bench`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/tools.rs"],
    },
    SurfaceBaseline {
        id: 93,
        name: "`lpm ci env`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::NotApplicable,
        references: &["tests/workflows/tests/ci.rs"],
    },
    SurfaceBaseline {
        id: 94,
        name: "`lpm ci setup github-actions`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/ci.rs"],
    },
    SurfaceBaseline {
        id: 95,
        name: "`lpm ci setup gitlab`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/tests/oidc_setup_snippet_contract.rs",
            "tests/workflows/tests/ci.rs",
        ],
    },
    SurfaceBaseline {
        id: 96,
        name: "`lpm env init`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/env/inventory.rs",
            "tests/workflows/tests/env_local.rs",
        ],
    },
    SurfaceBaseline {
        id: 97,
        name: "`lpm env ls / list`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_local.rs"],
    },
    SurfaceBaseline {
        id: 98,
        name: "`lpm env set / get / delete`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_local.rs"],
    },
    SurfaceBaseline {
        id: 99,
        name: "`lpm env import / export / print / copy`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_local.rs"],
    },
    SurfaceBaseline {
        id: 100,
        name: "`lpm env diff / validate / check`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_local.rs"],
    },
    SurfaceBaseline {
        id: 101,
        name: "`lpm env push / pull` (cloud)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/cross_command_flows.rs",
            "tests/workflows/tests/env_vault.rs",
        ],
    },
    SurfaceBaseline {
        id: 102,
        name: "`lpm env share`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_vault.rs"],
    },
    SurfaceBaseline {
        id: 103,
        name: "`lpm env pair`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_vault.rs"],
    },
    SurfaceBaseline {
        id: 104,
        name: "`lpm env unpair`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/env_local.rs",
            "tests/workflows/tests/env_vault.rs",
        ],
    },
    SurfaceBaseline {
        id: 105,
        name: "`lpm env connect / status / log / rotate-key / list-remote`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_vault.rs"],
    },
    SurfaceBaseline {
        id: 106,
        name: "`lpm env oidc allow`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_vault.rs"],
    },
    SurfaceBaseline {
        id: 107,
        name: "`lpm env oidc list`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_vault.rs"],
    },
    SurfaceBaseline {
        id: 108,
        name: "`lpm env oidc pull`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/env_vault.rs"],
    },
    SurfaceBaseline {
        id: 109,
        name: "`lpm dev`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::NotApplicable,
        references: &[
            "crates/lpm-cli/src/commands/dev.rs",
            "tests/workflows/tests/dev_tunnel.rs",
        ],
    },
    SurfaceBaseline {
        id: 110,
        name: "`lpm dev --tunnel / --https / --network`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::NotApplicable,
        references: &["tests/workflows/tests/dev_tunnel.rs"],
    },
    SurfaceBaseline {
        id: 111,
        name: "`lpm cert status / trust / uninstall / generate`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/cert.rs"],
    },
    SurfaceBaseline {
        id: 112,
        name: "`lpm graph` (tree default)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/graph.rs",
            "tests/workflows/tests/graph.rs",
        ],
    },
    SurfaceBaseline {
        id: 113,
        name: "`lpm graph --format json`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/graph.rs"],
    },
    SurfaceBaseline {
        id: 114,
        name: "`lpm graph --format html`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/graph.rs"],
    },
    SurfaceBaseline {
        id: 115,
        name: "`lpm graph --format dot / mermaid / stats`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/graph.rs"],
    },
    SurfaceBaseline {
        id: 116,
        name: "`lpm graph --why <pkg>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/graph.rs"],
    },
    SurfaceBaseline {
        id: 117,
        name: "`lpm ports list / all / inspect / kill / reset`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/ports.rs",
            "crates/lpm-runner/src/ports.rs",
            "tests/workflows/tests/ports.rs",
        ],
    },
    SurfaceBaseline {
        id: 118,
        name: "`lpm tunnel <port>` (start)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/tunnel.rs",
            "tests/workflows/tests/dev_tunnel.rs",
        ],
    },
    SurfaceBaseline {
        id: 119,
        name: "`lpm tunnel claim / unclaim / list / domains`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/dev_tunnel.rs"],
    },
    SurfaceBaseline {
        id: 120,
        name: "`lpm tunnel inspect / replay / log`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/dev_tunnel.rs"],
    },
    SurfaceBaseline {
        id: 121,
        name: "`lpm migrate` (auto-detect npm/yarn/pnpm/bun)",
        unit: true,
        integration: true,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/migrate_overrides.rs",
            "crates/lpm-cli/src/commands/migrate_patches.rs",
            "tests/integration/tests/output_parity.rs",
            "tests/workflows/tests/migrate.rs",
            "tests/workflows/tests/json_output.rs",
        ],
    },
    SurfaceBaseline {
        id: 122,
        name: "`lpm migrate --rollback`",
        unit: true,
        integration: true,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/integration/tests/core.rs",
            "tests/workflows/tests/migrate.rs",
        ],
    },
    SurfaceBaseline {
        id: 123,
        name: "`lpm migrate --dry-run`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "tests/workflows/tests/migrate.rs",
            "tests/workflows/tests/json_output.rs",
        ],
    },
    SurfaceBaseline {
        id: 124,
        name: "`lpm migrate --ci / --no-npmrc`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/migrate.rs"],
    },
    SurfaceBaseline {
        id: 125,
        name: "`lpm vault open / update / version`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/vault.rs"],
    },
    SurfaceBaseline {
        id: 126,
        name: "`lpm self-update`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/self_update.rs",
            "tests/workflows/tests/self_update.rs",
        ],
    },
    SurfaceBaseline {
        id: 127,
        name: "`lpm internal-update-check` (hidden)",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::NotApplicable,
        references: &["tests/workflows/tests/dev_tunnel.rs"],
    },
    SurfaceBaseline {
        id: 128,
        name: "`lpm swift-registry`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/swift_registry.rs",
            "tests/workflows/tests/swift.rs",
        ],
    },
    SurfaceBaseline {
        id: 129,
        name: "`lpm mcp setup / remove / status`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/mcp.rs",
            "tests/workflows/tests/mcp.rs",
        ],
    },
    SurfaceBaseline {
        id: 130,
        name: "`lpm use node@<v>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/use.rs",
            "tests/workflows/tests/use.rs",
        ],
    },
    SurfaceBaseline {
        id: 131,
        name: "`lpm use --list`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/use.rs"],
    },
    SurfaceBaseline {
        id: 132,
        name: "`lpm completions <shell>`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::NotApplicable,
        references: &["tests/workflows/tests/completions.rs"],
    },
    SurfaceBaseline {
        id: 133,
        name: "`lpm schema lpm.json`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/schema.rs",
            "crates/lpm-cli/tests/schema_drift.rs",
            "tests/workflows/tests/schema.rs",
        ],
    },
    SurfaceBaseline {
        id: 134,
        name: "`lpm schema lpm.config.json`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/tests/schema_drift.rs",
            "tests/workflows/tests/schema.rs",
        ],
    },
    SurfaceBaseline {
        id: 135,
        name: "`lpm strict-ssl warning` (cross-cmd installer warning)",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/install.rs"],
    },
    // These two surfaces cover install-pipeline behavior that's
    // orthogonal to lockfile fast-path (id 12), add-and-install
    // (id 13), --offline (id 14), workspace (id 15), policy (id 17),
    // strict-integrity (id 18), or strict-ssl (id 135). Folding them
    // into id 12 would make id 12's failure_modes_tested list too
    // broad to guide the coverage audit.
    SurfaceBaseline {
        id: 136,
        name: "`lpm install` pnpm migration warnings (cross-cmd)",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/install.rs"],
    },
    SurfaceBaseline {
        id: 137,
        name: "`lpm install` linker validation (LPM_LINKER env + CLI flag)",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/install.rs"],
    },
    SurfaceBaseline {
        id: 138,
        name: "`lpm bundle`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/bundle.rs",
            "tests/workflows/tests/bundle.rs",
        ],
    },
    SurfaceBaseline {
        id: 139,
        name: "`lpm pack`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/pack.rs",
            "tests/workflows/tests/pack.rs",
        ],
    },
    SurfaceBaseline {
        id: 140,
        name: "`lpm catalog list --unused`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/pnpm_compat_catalog.rs"],
    },
    SurfaceBaseline {
        id: 141,
        name: "`lpm catalog show --resolved`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/pnpm_compat_catalog.rs"],
    },
    SurfaceBaseline {
        id: 142,
        name: "`lpm patch-remove <selector>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/patch.rs",
            "tests/workflows/tests/patch.rs",
        ],
    },
    SurfaceBaseline {
        id: 143,
        name: "`lpm sbom`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/sbom.rs",
            "tests/workflows/tests/sbom.rs",
        ],
    },
    SurfaceBaseline {
        id: 144,
        name: "`lpm proxy status / list / start / stop`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: true,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/proxy.rs",
            "crates/lpm-cli/tests/proxy_status_contract.rs",
            "crates/lpm-proxy/src/lib.rs",
            "tests/workflows/tests/local_domains.rs",
        ],
    },
    SurfaceBaseline {
        id: 145,
        name: "`lpm hosts clean`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/hosts.rs",
            "crates/lpm-runner/src/local_domains.rs",
            "tests/workflows/tests/hosts.rs",
        ],
    },
    SurfaceBaseline {
        id: 146,
        name: "`lpm stage publish`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/npm_stage.rs",
            "crates/lpm-cli/src/commands/stage.rs",
            "tests/workflows/tests/stage.rs",
        ],
    },
    SurfaceBaseline {
        id: 147,
        name: "`lpm stage publish --dry-run`",
        unit: false,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &["tests/workflows/tests/stage.rs"],
    },
    SurfaceBaseline {
        id: 148,
        name: "`lpm stage list [package]`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/npm_stage.rs",
            "tests/workflows/tests/stage.rs",
        ],
    },
    SurfaceBaseline {
        id: 149,
        name: "`lpm stage view <stage-id>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/npm_stage.rs",
            "tests/workflows/tests/stage.rs",
        ],
    },
    SurfaceBaseline {
        id: 150,
        name: "`lpm stage approve <stage-id>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/npm_stage.rs",
            "tests/workflows/tests/stage.rs",
        ],
    },
    SurfaceBaseline {
        id: 151,
        name: "`lpm stage reject <stage-id>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/npm_stage.rs",
            "tests/workflows/tests/stage.rs",
        ],
    },
    SurfaceBaseline {
        id: 152,
        name: "`lpm stage download <stage-id>`",
        unit: true,
        integration: false,
        workflow: true,
        cli_binary: false,
        json_contract: JsonContractStatus::Covered,
        references: &[
            "crates/lpm-cli/src/commands/npm_stage.rs",
            "tests/workflows/tests/stage.rs",
        ],
    },
];
