mod support;

use sha2::{Digest, Sha256};
use support::mock_registry::MockRegistry;
use support::{TempProject, lpm_with_registry};

const FIRST_TOKEN_ID: &str = "11111111-1111-4111-8111-111111111111";

#[tokio::test]
async fn setup_local_json_writes_scoped_config_gitignore_and_read_only_token() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_replace(14, "2030-01-02T03:04:05Z", 1)
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local", "--days", "14", "--json"])
        .output()
        .expect("failed to run lpm setup local --json");

    assert!(
        output.status.success(),
        "lpm setup local --json failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let envelope: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("setup local --json must be valid JSON: {e}\n---\n{stdout}"));

    assert_eq!(envelope["success"], serde_json::json!(true));
    assert_eq!(envelope["proxy"], serde_json::json!(false));
    assert_eq!(envelope["expiry_days"], serde_json::json!(14));
    assert_eq!(
        envelope["expires_at"],
        serde_json::json!("2030-01-02T03:04:05Z")
    );
    assert_eq!(envelope["gitignore_updated"], serde_json::json!(true));
    assert_eq!(envelope["scope"], serde_json::json!("read"));
    assert!(
        !stdout.contains("lpm_read_only_token"),
        "JSON output must never expose the child token"
    );

    insta::with_settings!({
        filters => vec![
            (r#""/[^"]+/\.npmrc""#, r#""[NPMRC_PATH]""#),
            (r#""/[^"]+/\.gitignore""#, r#""[GITIGNORE_PATH]""#),
        ],
    }, {
        insta::assert_json_snapshot!("setup_local_json_envelope_writes_scoped_config", envelope);
    });

    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("# LPM Registry (generated by lpm setup local — do not commit)"),
        ".npmrc must identify the current command name, got:\n{npmrc}"
    );
    assert!(
        npmrc.contains(&format!("@lpm.dev:registry={}/api/registry", mock.url())),
        ".npmrc must use scoped routing by default, got:\n{npmrc}"
    );
    assert!(
        npmrc.lines().any(|line| {
            line.split_once("/:_authToken=").is_some_and(|(_, token)| {
                token.len() == 68
                    && token.starts_with("lpm_")
                    && token[4..].bytes().all(|byte| byte.is_ascii_hexdigit())
            })
        }),
        ".npmrc must contain a generated read-only token, got:\n{npmrc}"
    );
    assert_eq!(project.read_file(".gitignore"), ".npmrc\n");

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        let mode = std::fs::metadata(project.path().join(".npmrc"))
            .expect(".npmrc must exist")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600, ".npmrc must be owner-only on unix");
    }

    let requests = mock
        .server()
        .received_requests()
        .await
        .expect("wiremock request log must be available");
    assert_eq!(
        requests.len(),
        1,
        "expected exactly one atomic token-replacement request"
    );

    let body: serde_json::Value =
        serde_json::from_slice(&requests[0].body).expect("token-replacement body must be JSON");
    assert_eq!(
        requests[0].url.path(),
        "/api/registry/-/token/replace-project"
    );
    assert_eq!(body["scope"], serde_json::json!("read"));
    assert_eq!(body["expiryDays"], serde_json::json!(14));
    assert!(
        body["token"]
            .as_str()
            .is_some_and(|token| token.len() == 68)
    );
    assert!(body["tokenId"].as_str().is_some_and(|id| id.len() == 36));
    assert!(
        body["name"]
            .as_str()
            .expect("token-create name must be a string")
            .starts_with("npmrc-web-app-"),
        "token name must derive from the package name, got body:\n{}",
        serde_json::to_string_pretty(&body).unwrap()
    );
}

#[tokio::test]
async fn setup_local_rerun_replaces_only_generated_block_and_deduplicates_gitignore() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    project.write_file(
        ".npmrc",
        "registry=https://registry.example.test/\nfund=false\n",
    );
    project.write_file(".gitignore", "target\n.npmrc\n.npmrc\n");
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_replace(30, "2030-01-02T03:04:05Z", 2)
        .await;

    for _ in 0..2 {
        let output = lpm_with_registry(&project, &mock.url())
            .args(["setup", "local"])
            .output()
            .expect("run setup local");
        assert!(output.status.success());
    }

    let npmrc = project.read_file(".npmrc");
    assert_eq!(npmrc.matches("# LPM Registry (generated").count(), 1);
    assert_eq!(npmrc.matches("@lpm.dev:registry=").count(), 1);
    assert_eq!(npmrc.matches("_authToken=").count(), 1);
    assert!(npmrc.contains("registry=https://registry.example.test/"));
    assert!(npmrc.contains("fund=false"));
    assert_eq!(
        project
            .read_file(".gitignore")
            .lines()
            .filter(|line| line.trim() == ".npmrc")
            .count(),
        1
    );

    let requests = mock.server().received_requests().await.unwrap();
    assert_eq!(requests.len(), 2);
    assert!(
        requests
            .iter()
            .all(|request| request.url.path() == "/api/registry/-/token/replace-project")
    );
    let first: serde_json::Value = serde_json::from_slice(&requests[0].body).unwrap();
    let second: serde_json::Value = serde_json::from_slice(&requests[1].body).unwrap();
    assert_eq!(second["previousTokenId"], first["tokenId"]);
    assert_ne!(second["tokenId"], first["tokenId"]);
    assert_ne!(second["token"], first["token"]);
    assert!(npmrc.contains(second["tokenId"].as_str().unwrap()));
    assert!(npmrc.contains(second["token"].as_str().unwrap()));
    assert!(!npmrc.contains(first["token"].as_str().unwrap()));
}

#[tokio::test]
async fn setup_local_upgrades_an_unmarked_generated_token_with_one_atomic_replacement() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let previous_token = "lpm_pre_marker_read_only_token";
    let mock = MockRegistry::start().await;
    project.write_file(
        ".npmrc",
        &format!(
            "# LPM Registry (generated by lpm setup local — do not commit)\n\
             @lpm.dev:registry={}/api/registry\n\
             {}/api/registry/:_authToken={previous_token}\n\
             # End LPM Registry\n",
            mock.url(),
            mock.url().replace("http:", "")
        ),
    );
    project.write_file(".gitignore", ".npmrc\n");
    mock.with_npmrc_token_replace(30, "2030-01-02T03:04:05Z", 1)
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local against a pre-marker generated block");

    assert!(
        output.status.success(),
        "upgrade-safe replacement failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let requests = mock.server().received_requests().await.unwrap();
    assert_eq!(
        requests.len(),
        1,
        "replacement must be one Registry mutation"
    );
    assert_eq!(
        requests[0].url.path(),
        "/api/registry/-/token/replace-project"
    );
    let body: serde_json::Value =
        serde_json::from_slice(&requests[0].body).expect("replacement body must be JSON");
    assert_eq!(
        body["previousTokenHash"],
        hex::encode(Sha256::digest(previous_token.as_bytes()))
    );
}

#[cfg(unix)]
#[tokio::test]
async fn setup_local_npmrc_write_failure_happens_before_registry_mutation() {
    use std::os::unix::fs::PermissionsExt;

    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    project.write_file(".gitignore", ".npmrc\n");
    let mock = MockRegistry::start().await;
    let original_mode = std::fs::metadata(project.path())
        .expect("project metadata")
        .permissions()
        .mode();
    std::fs::set_permissions(
        project.path(),
        std::fs::Permissions::from_mode(original_mode & !0o222),
    )
    .expect("make project directory read-only");

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local with an npmrc commit failure");

    std::fs::set_permissions(
        project.path(),
        std::fs::Permissions::from_mode(original_mode),
    )
    .expect("restore project directory permissions");
    assert!(!output.status.success());
    assert_eq!(project.read_file(".gitignore"), ".npmrc\n");
    assert!(!project.file_exists(".npmrc"));
    let requests = mock.server().received_requests().await.unwrap();
    assert!(
        requests.is_empty(),
        "the recoverable .npmrc must commit before any Registry mutation"
    );
}

#[cfg(unix)]
#[tokio::test]
async fn setup_local_gitignore_write_failure_happens_before_token_creation() {
    use std::os::unix::fs::PermissionsExt;

    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    project.write_file(".gitignore", "target\n");
    let mock = MockRegistry::start().await;
    let original_mode = std::fs::metadata(project.path())
        .expect("project metadata")
        .permissions()
        .mode();
    std::fs::set_permissions(
        project.path(),
        std::fs::Permissions::from_mode(original_mode & !0o222),
    )
    .expect("make project directory read-only");

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local with an unwritable gitignore");

    std::fs::set_permissions(
        project.path(),
        std::fs::Permissions::from_mode(original_mode),
    )
    .expect("restore project directory permissions");
    assert!(!output.status.success());
    assert_eq!(project.read_file(".gitignore"), "target\n");
    assert!(!project.file_exists(".npmrc"));
    assert!(
        mock.server()
            .received_requests()
            .await
            .expect("wiremock request log")
            .is_empty(),
        "no token may be minted before .gitignore commits"
    );
}

#[tokio::test]
async fn setup_local_ambiguous_replacement_reuses_pending_credentials_on_retry() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_replace_ambiguous_then_success(30, "2030-01-02T03:04:05Z")
        .await;

    let first = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local with an ambiguous replacement response");

    assert!(!first.status.success());
    let pending = project.read_file(".npmrc");
    assert!(pending.contains("# LPM pending project token id: "));
    assert!(!pending.contains("# LPM project token id: "));
    assert_eq!(project.read_file(".gitignore"), ".npmrc\n");

    let second = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("retry setup local after an ambiguous replacement response");
    assert!(
        second.status.success(),
        "retry must finish the same idempotent operation:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&second.stdout),
        String::from_utf8_lossy(&second.stderr)
    );
    let final_npmrc = project.read_file(".npmrc");
    assert!(!final_npmrc.contains("# LPM pending project token id: "));
    assert!(final_npmrc.contains("# LPM project token id: "));

    let requests = mock.server().received_requests().await.unwrap();
    assert_eq!(requests.len(), 2);
    let first_body: serde_json::Value = serde_json::from_slice(&requests[0].body).unwrap();
    let second_body: serde_json::Value = serde_json::from_slice(&requests[1].body).unwrap();
    assert_eq!(first_body["tokenId"], second_body["tokenId"]);
    assert_eq!(first_body["token"], second_body["token"]);
    assert!(requests.iter().all(|request| {
        serde_json::from_slice::<serde_json::Value>(&request.body).is_ok_and(|body| {
            body["tokenId"] == first_body["tokenId"] && body["token"] == first_body["token"]
        })
    }));
    assert!(final_npmrc.contains(first_body["tokenId"].as_str().unwrap()));
    assert!(final_npmrc.contains(first_body["token"].as_str().unwrap()));
}

#[tokio::test]
async fn setup_local_bounded_registry_rejection_restores_pre_request_files() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let original_npmrc = "registry=https://registry.example.test/\nfund=false\n";
    project.write_file(".npmrc", original_npmrc);
    project.write_file(".gitignore", "target\n");
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_replace_error(400).await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local with a bounded Registry rejection");

    assert!(!output.status.success());
    assert_eq!(project.read_file(".npmrc"), original_npmrc);
    assert_eq!(project.read_file(".gitignore"), "target\n");
    assert_eq!(
        mock.server().received_requests().await.unwrap().len(),
        1,
        "bounded client errors must not be retried"
    );
}

#[tokio::test]
async fn setup_local_redacts_a_generated_token_echoed_by_a_registry_error() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_replace_echoed_token_error().await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local with a Registry error that echoes the token");

    assert!(!output.status.success());
    let requests = mock.server().received_requests().await.unwrap();
    let body: serde_json::Value =
        serde_json::from_slice(&requests[0].body).expect("replacement body must be JSON");
    let generated_token = body["token"].as_str().expect("request must contain token");
    let rendered = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        !rendered.contains(generated_token),
        "Registry-controlled errors must not disclose the generated bearer"
    );
    assert!(rendered.contains("<redacted>"));
}

#[tokio::test]
async fn setup_local_stray_end_marker_does_not_extend_an_unterminated_generated_block() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    project.write_file(
        ".npmrc",
        &format!(
            "# End LPM Registry\n\
             # LPM Registry (generated by lpm setup local — do not commit)\n\
             @lpm.dev:registry={}/api/registry/\n\
             {}/api/registry/:_authToken=lpm_stale-token\n\
             fund=false\n",
            mock.url(),
            mock.url().replace("http:", "")
        ),
    );
    mock.with_npmrc_token_replace(30, "2030-01-02T03:04:05Z", 1)
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local against unterminated generated block");

    assert!(
        output.status.success(),
        "setup failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("fund=false"),
        "an earlier stray end marker must not cause unrelated trailing config to be dropped:\n{npmrc}"
    );
    assert!(npmrc.contains("# LPM project token id: "));
    assert!(!npmrc.contains("lpm_stale-token"));
}

#[tokio::test]
async fn setup_local_proxy_flag_is_rejected_before_token_request() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local", "--proxy"])
        .output()
        .expect("failed to run lpm setup local --proxy");

    assert!(
        !output.status.success(),
        "lpm setup local --proxy must be rejected"
    );
    assert!(
        !project.file_exists(".npmrc"),
        "rejected --proxy setup must not write .npmrc"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("--proxy"),
        "rejection must name the removed flag, got:\n{stderr}"
    );

    let requests = mock
        .server()
        .received_requests()
        .await
        .expect("wiremock request log must be available");
    assert!(
        requests.is_empty(),
        "rejected --proxy setup must not request a token"
    );
}

#[tokio::test]
async fn setup_local_rejects_invalid_days_and_removed_scoped_before_network_or_writes() {
    for args in [
        vec!["setup", "local", "--days", "0"],
        vec!["setup", "local", "--days", "91"],
        vec!["setup", "local", "--scoped"],
    ] {
        let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
        let mock = MockRegistry::start().await;

        let output = lpm_with_registry(&project, &mock.url())
            .args(args)
            .output()
            .expect("run rejected setup local");

        assert!(!output.status.success());
        assert!(!project.file_exists(".npmrc"));
        assert!(!project.file_exists(".gitignore"));
        let requests = mock.server().received_requests().await.unwrap();
        assert!(requests.is_empty(), "rejected setup must be network-free");
    }
}

#[tokio::test]
async fn setup_local_malformed_success_response_retains_recoverable_pending_state() {
    for response in [
        serde_json::json!({
            "tokenId": FIRST_TOKEN_ID,
            "scope": "publish",
            "expiresAt": "2030-01-02T03:04:05Z"
        }),
        serde_json::json!({
            "tokenId": FIRST_TOKEN_ID,
            "scope": "read",
            "expiresAt": "not-a-timestamp"
        }),
        serde_json::json!({
            "tokenId": FIRST_TOKEN_ID,
            "expiresAt": "2030-01-02T03:04:05Z"
        }),
        serde_json::json!({
            "scope": "read",
            "expiresAt": "2030-01-02T03:04:05Z"
        }),
    ] {
        let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
        let mock = MockRegistry::start().await;
        mock.with_npmrc_token_replace_response(response).await;

        let output = lpm_with_registry(&project, &mock.url())
            .args(["setup", "local"])
            .output()
            .expect("run setup local with malformed response");

        assert!(!output.status.success());
        let npmrc = project.read_file(".npmrc");
        assert!(npmrc.contains("# LPM pending project token id: "));
        assert!(npmrc.contains("/:_authToken=lpm_"));
        assert_eq!(project.read_file(".gitignore"), ".npmrc\n");
    }
}

#[tokio::test]
async fn setup_local_non_json_output_uses_current_command_name() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_replace(30, "2030-01-02T03:04:05Z", 1)
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("failed to run lpm setup local");

    assert!(
        output.status.success(),
        "lpm setup local failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("# LPM Registry (generated by lpm setup local — do not commit)"),
        ".npmrc must identify the current command name, got:\n{npmrc}"
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.trim().is_empty(),
        "human setup local should not write to stdout, got:\n{stdout}"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("› Creating read-only token..."),
        "human setup local should announce token creation with the slim phase line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("✓ Read-only token created."),
        "human setup local should report token creation with the slim done line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("✓ .npmrc configured with read-only LPM token."),
        "human setup local should report final success with the slim done line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› .npmrc added to .gitignore to prevent token leaks."),
        "human setup local should keep the gitignore note on a slim info line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› Only @lpm.dev packages will route through lpm.dev."),
        "human setup local should keep the scoped-routing note on a slim info line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› Token expires: 2030-01-02T03:04:05Z"),
        "human setup local should keep the expiry line on a slim info line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("(30 days)"),
        "human setup local should show the token lifetime, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› Run `lpm setup local` again to refresh when expired."),
        "human setup local should mention the current command name on the slim info line, got:\n{stderr}"
    );
    assert!(
        !stderr.contains("●") && !stderr.contains("◆") && !stderr.contains("│"),
        "legacy cliclack glyphs must be gone from setup local stderr, got:\n{stderr}"
    );

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        combined.contains("Run `lpm setup local` again to refresh when expired."),
        "output must mention the current command name, got:\n{combined}"
    );
    assert!(
        !combined.contains("Run `lpm npmrc` again"),
        "legacy command name must not leak into output, got:\n{combined}"
    );
}

#[tokio::test]
async fn setup_local_color_output_dims_expiry_label_and_highlights_lifetime() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_replace(30, "2030-01-02T03:04:05Z", 1)
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["--color=always", "setup", "local"])
        .output()
        .expect("failed to run colored lpm setup local");

    assert!(
        output.status.success(),
        "colored setup local failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("\x1b[2mToken expires:")
            && stderr.contains("\x1b[33m30 days")
            && stderr.contains(".npmrc configured"),
        "setup local should dim the expiry label, highlight the lifetime, and keep .npmrc plain, got:\n{stderr:?}",
    );
}
