//! Workflow tests for `lpm setup ci npmrc` (CI `.npmrc` generation).
//!
//! The OIDC contract paths are pinned by the cli-binary survivor
//! [`crates/lpm-cli/tests/oidc_setup_snippet_contract.rs`]. This file
//! covers the non-OIDC branches that don't need a real CI environment:
//!
//! - scoped registry config (default)
//! - removed `--proxy` flag is rejected before writing `.npmrc`
//! - legacy `proxy = true` config no longer widens `.npmrc`
//! - `--registry <url>` overrides the registry URL
//! - JSON envelope shape (path, content, uses_env_var, oidc, proxy)
//! - missing-token failure leaves the project unchanged

mod support;

use support::auth_state::{SessionSeed, seed_sessions};
use support::{TempProject, lpm};

// ─── default scoped config ────────────────────────────────────────────

#[test]
fn setup_ci_without_bearer_fails_before_writing_dot_npmrc() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);

    let output = lpm(&project)
        .args([
            "--registry",
            "https://lpm.example.test",
            "setup",
            "ci",
            "npmrc",
        ])
        .output()
        .expect("failed to run lpm setup ci npmrc");

    assert!(!output.status.success(), "missing bearer must fail");
    assert!(
        !project.file_exists(".npmrc"),
        "failure must not write .npmrc"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("LPM_TOKEN") && stderr.contains("lpm login"),
        "failure must explain how to supply a bearer, got:\n{stderr}"
    );
}

#[test]
fn setup_ci_writes_literal_env_bearer_and_preserves_unrelated_config() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    std::fs::write(
        project.path().join(".npmrc"),
        "registry=https://registry.example.test/\nfund=false\n",
    )
    .expect("seed .npmrc");

    let output = lpm(&project)
        .env("LPM_TOKEN", "ci-runtime-token")
        .args([
            "--registry",
            "https://lpm.example.test",
            "setup",
            "ci",
            "npmrc",
        ])
        .output()
        .expect("failed to run lpm setup ci npmrc --color=always");

    assert!(output.status.success(), "lpm setup ci npmrc failed");
    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("registry=https://registry.example.test/")
            && npmrc.contains("fund=false")
            && npmrc.contains("@lpm.dev:registry=https://lpm.example.test/api/registry/")
            && npmrc.contains("ci-runtime-token"),
        "generated block must preserve unrelated config and contain the resolved bearer:\n{npmrc}"
    );
    assert!(
        !npmrc.contains("${LPM_TOKEN}"),
        "project .npmrc must not contain sensitive environment expansion"
    );

    let mut parsed = lpm_registry::npmrc::NpmrcConfig::parse_layer_with_options(
        &npmrc,
        "project/.npmrc",
        Some(project.path()),
        true,
        &|_| None,
    );
    parsed.finalize();
    assert!(
        parsed.security_warnings.is_empty() && parsed.errors.is_empty(),
        "generated project layer must pass the real trust parser: {:?} {:?}",
        parsed.security_warnings,
        parsed.errors
    );
    assert!(parsed.scope_registries.contains_key("@lpm.dev"));
    assert!(
        parsed
            .auth_for_url("https://lpm.example.test/api/registry/@lpm.dev/pkg")
            .is_some(),
        "generated literal bearer must resolve for the scoped registry origin"
    );
}

#[test]
fn setup_ci_replaces_unterminated_generated_block_without_dropping_following_config() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    std::fs::write(
        project.path().join(".npmrc"),
        "# LPM Registry (generated by lpm setup ci npmrc)\n\
         //lpm.example.test/:_authToken=stale-token\n\
         @lpm.dev:registry=https://lpm.example.test/api/registry/\n\
         fund=false\n",
    )
    .expect("seed unterminated generated block");

    let output = lpm(&project)
        .env("LPM_TOKEN", "replacement-token")
        .args([
            "--registry",
            "https://lpm.example.test",
            "setup",
            "ci",
            "npmrc",
        ])
        .output()
        .expect("run setup ci against unterminated block");

    assert!(
        output.status.success(),
        "setup failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let npmrc = project.read_file(".npmrc");
    assert!(npmrc.contains("fund=false"));
    assert!(npmrc.contains("replacement-token"));
    assert!(!npmrc.contains("stale-token"));
}

#[test]
fn setup_ci_stray_end_marker_does_not_extend_an_unterminated_generated_block() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    std::fs::write(
        project.path().join(".npmrc"),
        "# End LPM Registry\n\
         # LPM Registry (generated by lpm setup ci npmrc)\n\
         //lpm.example.test/:_authToken=stale-token\n\
         @lpm.dev:registry=https://lpm.example.test/api/registry/\n\
         fund=false\n",
    )
    .expect("seed generated block with a stray earlier end marker");

    let output = lpm(&project)
        .env("LPM_TOKEN", "lpm_replacement-token")
        .args([
            "--registry",
            "https://lpm.example.test",
            "setup",
            "ci",
            "npmrc",
        ])
        .output()
        .expect("run setup ci against unterminated block");

    assert!(
        output.status.success(),
        "setup failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("fund=false"),
        "an earlier stray end marker must not cause unrelated trailing config to be dropped:\n{npmrc}"
    );
    assert!(npmrc.contains("lpm_replacement-token"));
    assert!(!npmrc.contains("stale-token"));
}

#[test]
fn setup_ci_rejects_malformed_bearer_before_writing_dot_npmrc() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);

    let output = lpm(&project)
        .env("LPM_TOKEN", "ci-token\u{1b}injected")
        .args(["setup", "ci", "npmrc"])
        .output()
        .expect("run setup ci with malformed bearer");

    assert!(!output.status.success());
    assert!(!project.file_exists(".npmrc"));
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("malformed"),
        "failure should identify the malformed bearer"
    );
}

#[test]
fn setup_ci_explicit_oidc_failure_does_not_fall_back_to_stored_token() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let registry_url = "https://lpm.example.test";
    seed_sessions(
        project.home(),
        &[SessionSeed {
            registry_url,
            access_token: Some("stored-token"),
            refresh_token: Some("refresh-token"),
            session_access_expires_at: Some("2030-01-01T00:00:00Z"),
        }],
    );

    let output = lpm(&project)
        .args(["--registry", registry_url, "setup", "ci", "npmrc", "--oidc"])
        .output()
        .expect("run setup ci with unavailable explicit OIDC");

    assert!(!output.status.success());
    assert!(!project.file_exists(".npmrc"));
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("no fallback was used"),
        "explicit OIDC failure should explain that stored credentials were not used"
    );
}

#[test]
fn setup_ci_proxy_flag_is_rejected_before_dot_npmrc_is_written() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);

    let output = lpm(&project)
        .args([
            "--registry",
            "https://lpm.example.test",
            "setup",
            "ci",
            "npmrc",
            "--proxy",
        ])
        .output()
        .expect("failed to run lpm setup ci npmrc --proxy");

    assert!(
        !output.status.success(),
        "lpm setup ci npmrc --proxy must be rejected"
    );
    assert!(
        !project.file_exists(".npmrc"),
        "rejected --proxy setup must not write .npmrc"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("--proxy"),
        "rejection must name the removed flag, got:\n{stderr}"
    );
}

#[test]
fn setup_ci_ignores_legacy_proxy_config_when_writing_dot_npmrc() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let lpm_dir = project.home().join(".lpm");
    std::fs::create_dir_all(&lpm_dir).expect("create isolated lpm home");
    std::fs::write(lpm_dir.join("config.toml"), "proxy = true\n")
        .expect("write legacy proxy config");

    let output = lpm(&project)
        .env("LPM_TOKEN", "ci-runtime-token")
        .args([
            "--registry",
            "https://lpm.example.test",
            "setup",
            "ci",
            "npmrc",
        ])
        .output()
        .expect("failed to run lpm setup ci npmrc");

    assert!(
        output.status.success(),
        "lpm setup ci npmrc failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let npmrc =
        std::fs::read_to_string(project.path().join(".npmrc")).expect("setup ci must write .npmrc");
    assert!(
        npmrc.contains("@lpm.dev:registry=https://lpm.example.test/api/registry/"),
        "legacy proxy config must not widen setup output, got:\n{npmrc}",
    );
    assert!(
        !npmrc.lines().any(|line| line.starts_with("registry=")),
        "legacy proxy config must not write a bare registry line, got:\n{npmrc}",
    );
}

// ─── --json envelope ──────────────────────────────────────────────────

#[test]
fn setup_ci_json_envelope_carries_path_content_and_flag_state() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);

    let output = lpm(&project)
        .env("LPM_TOKEN", "ci-runtime-token")
        .args([
            "--registry",
            "https://lpm.example.test",
            "--json",
            "setup",
            "ci",
            "npmrc",
        ])
        .output()
        .expect("failed to run lpm setup ci npmrc --json");

    assert!(output.status.success(), "lpm setup ci npmrc --json failed");

    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let envelope: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("setup ci --json must be valid JSON: {e}\n---\n{stdout}"));

    assert_eq!(envelope["success"], serde_json::json!(true));
    assert_eq!(envelope["proxy"], serde_json::json!(false));
    assert_eq!(envelope["oidc"], serde_json::json!(false));
    assert_eq!(envelope["uses_env_var"], serde_json::json!(true));
    assert_eq!(envelope["storage_backend"], serde_json::Value::Null);
    assert_eq!(envelope["storage_degraded"], serde_json::json!(false));

    let path = envelope["path"].as_str().expect("path must be a string");
    assert!(
        path.ends_with(".npmrc"),
        "envelope path must point at .npmrc, got: {path}"
    );

    let content = envelope["content"]
        .as_str()
        .expect("content must be a string");
    assert!(
        content.contains("@lpm.dev:registry=https://lpm.example.test/api/registry/"),
        "envelope content must include the scoped registry line, got:\n{content}",
    );
}

#[test]
fn setup_ci_scoped_flag_is_an_unknown_argument_without_writes() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);

    let output = lpm(&project)
        .env("LPM_TOKEN", "ci-runtime-token")
        .args(["setup", "ci", "npmrc", "--scoped"])
        .output()
        .expect("run setup ci with removed flag");

    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("--scoped"));
    assert!(!project.file_exists(".npmrc"));
}

#[test]
fn setup_ci_json_reports_file_backed_storage_backend_for_stored_token() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    let registry_url = "https://lpm.example.test";
    seed_sessions(
        project.home(),
        &[SessionSeed {
            registry_url,
            access_token: Some("stored-token"),
            refresh_token: None,
            session_access_expires_at: None,
        }],
    );

    let output = lpm(&project)
        .args(["--registry", registry_url, "--json", "setup", "ci", "npmrc"])
        .output()
        .expect("failed to run lpm setup ci npmrc --json");

    assert!(
        output.status.success(),
        "lpm setup ci npmrc --json with stored token failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let envelope: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("setup ci --json must be valid JSON: {e}\n---\n{stdout}"));

    assert_eq!(envelope["uses_env_var"], serde_json::json!(false));
    assert_eq!(
        envelope["storage_backend"],
        serde_json::json!("encrypted_file_fallback")
    );
    assert_eq!(envelope["storage_degraded"], serde_json::json!(true));
}
