mod support;

use support::mock_registry::MockRegistry;
use support::{TempProject, lpm_with_registry};

#[tokio::test]
async fn setup_local_json_writes_scoped_config_gitignore_and_read_only_token() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_create(14, "lpm_read_only_token", "2030-01-02T03:04:05Z")
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local", "--days", "14", "--json"])
        .output()
        .expect("failed to run lpm setup local --json");

    assert!(
        output.status.success(),
        "lpm setup local --json failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let envelope: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("setup local --json must be valid JSON: {e}\n---\n{stdout}"));

    assert_eq!(envelope["success"], serde_json::json!(true));
    assert_eq!(envelope["proxy"], serde_json::json!(false));
    assert_eq!(envelope["expiry_days"], serde_json::json!(14));
    assert_eq!(
        envelope["expires_at"],
        serde_json::json!("2030-01-02T03:04:05Z")
    );
    assert_eq!(envelope["gitignore_updated"], serde_json::json!(true));
    assert_eq!(envelope["scope"], serde_json::json!("read"));
    assert!(
        !stdout.contains("lpm_read_only_token"),
        "JSON output must never expose the child token"
    );

    insta::with_settings!({
        filters => vec![
            (r#""/[^"]+/\.npmrc""#, r#""[NPMRC_PATH]""#),
            (r#""/[^"]+/\.gitignore""#, r#""[GITIGNORE_PATH]""#),
        ],
    }, {
        insta::assert_json_snapshot!("setup_local_json_envelope_writes_scoped_config", envelope);
    });

    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("# LPM Registry (generated by lpm setup local — do not commit)"),
        ".npmrc must identify the current command name, got:\n{npmrc}"
    );
    assert!(
        npmrc.contains(&format!("@lpm.dev:registry={}/api/registry", mock.url())),
        ".npmrc must use scoped routing by default, got:\n{npmrc}"
    );
    assert!(
        npmrc.contains("lpm_read_only_token"),
        ".npmrc must contain the issued read-only token, got:\n{npmrc}"
    );
    assert_eq!(project.read_file(".gitignore"), ".npmrc\n");

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        let mode = std::fs::metadata(project.path().join(".npmrc"))
            .expect(".npmrc must exist")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600, ".npmrc must be owner-only on unix");
    }

    let requests = mock
        .server()
        .received_requests()
        .await
        .expect("wiremock request log must be available");
    assert_eq!(
        requests.len(),
        1,
        "expected exactly one token-create request"
    );

    let body: serde_json::Value =
        serde_json::from_slice(&requests[0].body).expect("token-create body must be JSON");
    assert_eq!(body["scope"], serde_json::json!("read"));
    assert_eq!(body["expiryDays"], serde_json::json!(14));
    assert!(
        body["name"]
            .as_str()
            .expect("token-create name must be a string")
            .starts_with("npmrc-web-app-"),
        "token name must derive from the package name, got body:\n{}",
        serde_json::to_string_pretty(&body).unwrap()
    );
}

#[tokio::test]
async fn setup_local_rerun_replaces_only_generated_block_and_deduplicates_gitignore() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    project.write_file(
        ".npmrc",
        "registry=https://registry.example.test/\nfund=false\n",
    );
    project.write_file(".gitignore", "target\n.npmrc\n.npmrc\n");
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_create_expected(30, "lpm_read_only_token", "2030-01-02T03:04:05Z", 2)
        .await;

    for _ in 0..2 {
        let output = lpm_with_registry(&project, &mock.url())
            .args(["setup", "local"])
            .output()
            .expect("run setup local");
        assert!(output.status.success());
    }

    let npmrc = project.read_file(".npmrc");
    assert_eq!(npmrc.matches("# LPM Registry (generated").count(), 1);
    assert_eq!(npmrc.matches("@lpm.dev:registry=").count(), 1);
    assert_eq!(npmrc.matches("_authToken=").count(), 1);
    assert!(npmrc.contains("registry=https://registry.example.test/"));
    assert!(npmrc.contains("fund=false"));
    assert_eq!(
        project
            .read_file(".gitignore")
            .lines()
            .filter(|line| line.trim() == ".npmrc")
            .count(),
        1
    );
}

#[tokio::test]
async fn setup_local_stray_end_marker_does_not_extend_an_unterminated_generated_block() {
    let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
    project.write_file(
        ".npmrc",
        "# End LPM Registry\n\
         # LPM Registry (generated by lpm setup local — do not commit)\n\
         @lpm.dev:registry=https://lpm.example.test/api/registry/\n\
         //lpm.example.test/api/registry/:_authToken=lpm_stale-token\n\
         fund=false\n",
    );
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_create(30, "lpm_replacement-token", "2030-01-02T03:04:05Z")
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("run setup local against unterminated generated block");

    assert!(
        output.status.success(),
        "setup failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("fund=false"),
        "an earlier stray end marker must not cause unrelated trailing config to be dropped:\n{npmrc}"
    );
    assert!(npmrc.contains("lpm_replacement-token"));
    assert!(!npmrc.contains("lpm_stale-token"));
}

#[tokio::test]
async fn setup_local_proxy_flag_is_rejected_before_token_request() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local", "--proxy"])
        .output()
        .expect("failed to run lpm setup local --proxy");

    assert!(
        !output.status.success(),
        "lpm setup local --proxy must be rejected"
    );
    assert!(
        !project.file_exists(".npmrc"),
        "rejected --proxy setup must not write .npmrc"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("--proxy"),
        "rejection must name the removed flag, got:\n{stderr}"
    );

    let requests = mock
        .server()
        .received_requests()
        .await
        .expect("wiremock request log must be available");
    assert!(
        requests.is_empty(),
        "rejected --proxy setup must not request a token"
    );
}

#[tokio::test]
async fn setup_local_rejects_invalid_days_and_removed_scoped_before_network_or_writes() {
    for args in [
        vec!["setup", "local", "--days", "0"],
        vec!["setup", "local", "--days", "91"],
        vec!["setup", "local", "--scoped"],
    ] {
        let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
        let mock = MockRegistry::start().await;

        let output = lpm_with_registry(&project, &mock.url())
            .args(args)
            .output()
            .expect("run rejected setup local");

        assert!(!output.status.success());
        assert!(!project.file_exists(".npmrc"));
        assert!(!project.file_exists(".gitignore"));
        let requests = mock.server().received_requests().await.unwrap();
        assert!(requests.is_empty(), "rejected setup must be network-free");
    }
}

#[tokio::test]
async fn setup_local_rejects_malformed_token_responses_before_writing_files() {
    for response in [
        serde_json::json!({
            "token": "lpm_read_only_token",
            "scope": "publish",
            "expiresAt": "2030-01-02T03:04:05Z"
        }),
        serde_json::json!({
            "token": "lpm_bad\nregistry=https://attacker.invalid",
            "scope": "read",
            "expiresAt": "2030-01-02T03:04:05Z"
        }),
        serde_json::json!({
            "token": "lpm_read_only_token",
            "scope": "read",
            "expiresAt": "not-a-timestamp"
        }),
    ] {
        let project = TempProject::empty(r#"{"name":"setup","version":"1.0.0"}"#);
        let mock = MockRegistry::start().await;
        mock.with_npmrc_token_create_response(response).await;

        let output = lpm_with_registry(&project, &mock.url())
            .args(["setup", "local"])
            .output()
            .expect("run setup local with malformed response");

        assert!(!output.status.success());
        assert!(!project.file_exists(".npmrc"));
        assert!(!project.file_exists(".gitignore"));
    }
}

#[tokio::test]
async fn setup_local_non_json_output_uses_current_command_name() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_create(30, "lpm_read_only_token", "2030-01-02T03:04:05Z")
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["setup", "local"])
        .output()
        .expect("failed to run lpm setup local");

    assert!(
        output.status.success(),
        "lpm setup local failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let npmrc = project.read_file(".npmrc");
    assert!(
        npmrc.contains("# LPM Registry (generated by lpm setup local — do not commit)"),
        ".npmrc must identify the current command name, got:\n{npmrc}"
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.trim().is_empty(),
        "human setup local should not write to stdout, got:\n{stdout}"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("› Creating read-only token..."),
        "human setup local should announce token creation with the slim phase line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("✓ Read-only token created."),
        "human setup local should report token creation with the slim done line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("✓ .npmrc configured with read-only LPM token."),
        "human setup local should report final success with the slim done line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› .npmrc added to .gitignore to prevent token leaks."),
        "human setup local should keep the gitignore note on a slim info line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› Only @lpm.dev packages will route through lpm.dev."),
        "human setup local should keep the scoped-routing note on a slim info line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› Token expires: 2030-01-02T03:04:05Z"),
        "human setup local should keep the expiry line on a slim info line, got:\n{stderr}"
    );
    assert!(
        stderr.contains("(30 days)"),
        "human setup local should show the token lifetime, got:\n{stderr}"
    );
    assert!(
        stderr.contains("› Run `lpm setup local` again to refresh when expired."),
        "human setup local should mention the current command name on the slim info line, got:\n{stderr}"
    );
    assert!(
        !stderr.contains("●") && !stderr.contains("◆") && !stderr.contains("│"),
        "legacy cliclack glyphs must be gone from setup local stderr, got:\n{stderr}"
    );

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        combined.contains("Run `lpm setup local` again to refresh when expired."),
        "output must mention the current command name, got:\n{combined}"
    );
    assert!(
        !combined.contains("Run `lpm npmrc` again"),
        "legacy command name must not leak into output, got:\n{combined}"
    );
}

#[tokio::test]
async fn setup_local_color_output_dims_expiry_label_and_highlights_lifetime() {
    let project = TempProject::empty(r#"{"name":"web app","version":"1.0.0"}"#);
    let mock = MockRegistry::start().await;
    mock.with_npmrc_token_create(30, "lpm_read_only_token", "2030-01-02T03:04:05Z")
        .await;

    let output = lpm_with_registry(&project, &mock.url())
        .args(["--color=always", "setup", "local"])
        .output()
        .expect("failed to run colored lpm setup local");

    assert!(
        output.status.success(),
        "colored setup local failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("\x1b[2mToken expires:")
            && stderr.contains("\x1b[33m30 days")
            && stderr.contains(".npmrc configured"),
        "setup local should dim the expiry label, highlight the lifetime, and keep .npmrc plain, got:\n{stderr:?}",
    );
}
